// Generated by scripts/gen-kit-looks.mjs. Do not edit by hand.
//
// The AI composer's style vocabulary: every presentation template's visual
// system, harvested as a named style the outline model can pick for a
// generated deck. A style is one complete system: a palette on paper and on
// a deep gradient ground, the display, body and accent faces, a corner
// radius, an ornament, a type scale and the drawings the template used. The
// composer sets a generated deck in one of these the way the template was
// set, so the deck reads as designed rather than derived.

import type { KitStyle } from "./look";

export const KIT_STYLES: Record<string, KitStyle> = {
 "campfire": {
  "name": "campfire",
  "from": "deck-team-offsite",
  "hint": "cream paper, pine ink, campfire orange and lake blue, rounded, a loose hand for the kicker, ridgelines and stars on the deep ground; offsites, community, outdoors, teams",
  "display": "Quicksand",
  "dw": 700,
  "body": "Figtree",
  "bw": 400,
  "mono": null,
  "accentFace": "Handlee",
  "accentWeight": 400,
  "accentSize": 40,
  "paper": {
   "bg": "#F7F3E9",
   "ink": "#1B3129",
   "muted": "#5B6A63",
   "line": "#D8D3C4",
   "panel": "#EEE9DC",
   "panel2": "#E3DECE",
   "accent": "#E0692A",
   "accent2": "#2E7EA6",
   "accentInk": "#9E3F0E",
   "accent2Ink": "#1D5F80",
   "sun": "#F0B64A"
  },
  "deep": {
   "bg": "#1C4757",
   "ink": "#F7F3E9",
   "muted": "#B5C9CF",
   "line": "#2F6274",
   "panel": "#25566A",
   "panel2": "#2E667C",
   "accent": "#F28E4E",
   "accent2": "#8FD3EA",
   "bg2": "#0D2A36",
   "accentInk": "#F9AE72",
   "sun": "#F0B64A"
  },
  "radius": 18,
  "ornament": "ridges",
  "scale": {
   "cover": 112,
   "title": 60,
   "section": 230,
   "statement": 78,
   "numeral": 104,
   "quote": 54
  },
  "art": {
   "cover": "il-day96-camping",
   "section": "il-day21-lantern",
   "picture": "il-day31-sweet-home",
   "closing": "il-day61-travel-bag"
  },
  "peeps": [
   "op-peep-31",
   "op-peep-44",
   "op-peep-67",
   "op-peep-77",
   "op-peep-94"
  ]
 },
 "sunny": {
  "name": "sunny",
  "from": "deck-all-hands",
  "hint": "warm cream, tomato and cobalt, a rounded friendly display, a sun in the corner; all-hands, celebrations, culture, internal news",
  "display": "Baloo 2",
  "dw": 700,
  "body": "Nunito",
  "bw": 500,
  "mono": null,
  "accentFace": "Kalam",
  "accentWeight": 700,
  "accentSize": 40,
  "paper": {
   "bg": "#FFF4E8",
   "ink": "#2B1D17",
   "muted": "#6E5A50",
   "line": "#EBD8C8",
   "panel": "#FFEBDB",
   "panel2": "#FCDFC9",
   "accent": "#E04A28",
   "accent2": "#2A4FCB",
   "accentInk": "#BE3C26",
   "sun": "#FFC857"
  },
  "deep": {
   "bg": "#2643B5",
   "ink": "#FFF4E8",
   "muted": "#C9D2F5",
   "line": "#4B66D1",
   "panel": "#3352C4",
   "panel2": "#3F5ED2",
   "accent": "#FF8F73",
   "accent2": "#FFC857",
   "bg2": "#172A78",
   "accentInk": "#FFC4B3",
   "sun": "#FFC857"
  },
  "radius": 20,
  "ornament": "sun",
  "scale": {
   "cover": 118,
   "title": 64,
   "section": 240,
   "statement": 80,
   "numeral": 108,
   "quote": 54
  },
  "art": {
   "cover": "la-small-character-illustrations",
   "section": "il-day52-auntum",
   "picture": "la-conversation-illustration",
   "closing": "il-day26-rainbow"
  },
  "peeps": [
   "op-peep-16",
   "op-peep-19",
   "op-peep-1",
   "op-peep-95",
   "op-peep-73",
   "op-peep-89",
   "op-peep-34"
  ]
 },
 "ledger": {
  "name": "ledger",
  "from": "deck-annual-report",
  "hint": "ivory paper, forest green and old gold, a Baskerville serif, a giant numeral watermark; annual reports, finance, heritage, formal reviews",
  "display": "Libre Baskerville",
  "dw": 600,
  "body": "Libre Franklin",
  "bw": 400,
  "mono": null,
  "accentFace": "Kalam",
  "accentWeight": 400,
  "accentSize": 38,
  "paper": {
   "bg": "#F6F1E6",
   "ink": "#1B2A22",
   "muted": "#5A655E",
   "line": "#D8D0BE",
   "panel": "#EEE7D7",
   "panel2": "#E4DCC7",
   "accent": "#1E5B45",
   "accent2": "#7F5E17"
  },
  "deep": {
   "bg": "#16483A",
   "ink": "#F6F1E6",
   "muted": "#B9C9BE",
   "line": "#2C5A4A",
   "panel": "#1E5546",
   "panel2": "#276353",
   "accent": "#D9B25A",
   "accent2": "#8FC9AC",
   "bg2": "#0A2A20",
   "accentInk": "#E2C06A"
  },
  "radius": 4,
  "ornament": "watermark",
  "scale": {
   "cover": 112,
   "title": 62,
   "section": 236,
   "statement": 80,
   "numeral": 100,
   "quote": 52
  },
  "art": {
   "cover": "il-day54-building",
   "section": "il-day35-firework",
   "picture": "il-day57-reading-room",
   "closing": "il-day65-city-road"
  },
  "peeps": [
   "op-peep-96",
   "op-peep-95",
   "op-peep-16",
   "op-peep-57",
   "op-peep-83"
  ],
  "watermark": "26"
 },
 "parchment": {
  "name": "parchment",
  "from": "deck-book-summary",
  "hint": "parchment, bottle green and brick, a Garamond serif with a pilcrow watermark; books, essays, reading groups, ideas, humanities",
  "display": "EB Garamond",
  "dw": 600,
  "body": "Lato",
  "bw": 400,
  "mono": null,
  "accentFace": "Reenie Beanie",
  "accentWeight": 400,
  "accentSize": 48,
  "paper": {
   "bg": "#F4EBDA",
   "ink": "#1E1A14",
   "muted": "#5E5648",
   "line": "#D8CCB4",
   "panel": "#EBE1CB",
   "panel2": "#E0D4BA",
   "accent": "#2F5F3F",
   "accent2": "#8C3A2E",
   "sun": "#C9A24E"
  },
  "deep": {
   "bg": "#17281E",
   "ink": "#F4EBDA",
   "muted": "#B7C3B2",
   "line": "#2C4436",
   "panel": "#1F3527",
   "panel2": "#284232",
   "accent": "#D9B45E",
   "accent2": "#A6CFA0",
   "bg2": "#0B140F"
  },
  "radius": 4,
  "ornament": "watermark",
  "scale": {
   "cover": 112,
   "title": 64,
   "section": 236,
   "statement": 80,
   "numeral": 100,
   "quote": 56
  },
  "art": {
   "cover": "il-day57-reading-room",
   "section": "la-conversation-illustration",
   "picture": "od-sitting-reading",
   "closing": "il-day22-owl"
  },
  "peeps": [
   "op-peep-3",
   "op-peep-31",
   "op-peep-43",
   "op-peep-50",
   "op-peep-94"
  ],
  "charWidth": 0.48,
  "strongWeight": 700,
  "watermark": "¶"
 },
 "newsprint": {
  "name": "newsprint",
  "from": "deck-budget-review",
  "hint": "cool white, navy and teal, a newspaper serif, a dot grid; budgets, planning, operations, public sector",
  "display": "Newsreader",
  "dw": 600,
  "body": "Public Sans",
  "bw": 400,
  "mono": "DM Mono",
  "accentFace": "Architects Daughter",
  "accentWeight": 400,
  "accentSize": 34,
  "paper": {
   "bg": "#F6F7F3",
   "ink": "#12284A",
   "muted": "#4B5B72",
   "line": "#D4DBD6",
   "panel": "#ECF1EC",
   "panel2": "#DFE8E1",
   "accent": "#1E4C8F",
   "accent2": "#1E7860"
  },
  "deep": {
   "bg": "#10305A",
   "ink": "#F3F6F1",
   "muted": "#AEBCCB",
   "line": "#27456E",
   "panel": "#183B69",
   "panel2": "#1F4676",
   "accent": "#7FDDC0",
   "accent2": "#9CC6F2",
   "bg2": "#081B36",
   "accentInk": "#93E6CC"
  },
  "radius": 4,
  "ornament": "dots",
  "scale": {
   "cover": 112,
   "title": 62,
   "section": 236,
   "statement": 80,
   "numeral": 104,
   "quote": 54
  },
  "art": {
   "cover": "il-day36-abacus",
   "section": "il-day6-open-vault",
   "picture": "il-day37-calculator",
   "closing": "il-day5-vault"
  },
  "peeps": [
   "op-peep-31",
   "op-peep-44",
   "op-peep-67",
   "op-peep-77",
   "op-peep-94"
  ]
 },
 "casebook": {
  "name": "casebook",
  "from": "deck-case-study",
  "hint": "white paper, royal blue and gold, a bookish serif with hairline rules; case studies, evidence, customer stories, consulting",
  "display": "Literata",
  "dw": 700,
  "body": "Fira Sans",
  "bw": 400,
  "mono": null,
  "accentFace": "Homemade Apple",
  "accentWeight": 400,
  "accentSize": 36,
  "paper": {
   "bg": "#FFFFFF",
   "ink": "#0E1B45",
   "muted": "#4A5674",
   "line": "#DCE1EE",
   "panel": "#F3F5FB",
   "panel2": "#E7ECF7",
   "accent": "#1F3FBF",
   "accent2": "#C99A22",
   "accent2Ink": "#8A6512",
   "sun": "#E9B949"
  },
  "deep": {
   "bg": "#1D3FA8",
   "ink": "#FFFFFF",
   "muted": "#C5D0F2",
   "line": "#3B5BC2",
   "panel": "#2847AD",
   "panel2": "#3558C4",
   "accent": "#F2C65C",
   "accent2": "#A9C1F5",
   "bg2": "#0D1F5E",
   "sun": "#F2C65C"
  },
  "radius": 4,
  "ornament": "hairlines",
  "scale": {
   "cover": 104,
   "title": 60,
   "section": 236,
   "statement": 80,
   "numeral": 100,
   "quote": 52
  },
  "art": {
   "cover": "il-day14-forklift",
   "section": "il-day37-calculator",
   "picture": "la-guy-with-glasses",
   "closing": "il-day17-walkie-talkie"
  },
  "peeps": [
   "op-peep-2",
   "op-peep-11",
   "op-peep-16",
   "op-peep-33",
   "op-peep-50"
  ],
  "charWidth": 0.57
 },
 "graphite": {
  "name": "graphite",
  "from": "deck-competitive-analysis",
  "hint": "white and graphite with one red, a condensed display and concentric arcs; competitive analysis, strategy, sport, hard news",
  "display": "Barlow Condensed",
  "dw": 700,
  "body": "Barlow",
  "bw": 400,
  "mono": "Chivo Mono",
  "accentFace": "Permanent Marker",
  "accentWeight": 400,
  "accentSize": 30,
  "paper": {
   "bg": "#FFFFFF",
   "ink": "#1B1D21",
   "muted": "#565B63",
   "line": "#D8DBDF",
   "panel": "#F1F2F4",
   "panel2": "#E2E4E8",
   "accent": "#E11D2B",
   "accent2": "#2B2F36",
   "accentInk": "#C4121F"
  },
  "deep": {
   "bg": "#272B31",
   "ink": "#F5F5F3",
   "muted": "#A9AEB6",
   "line": "#3E434A",
   "panel": "#31363D",
   "panel2": "#3C4149",
   "accent": "#FF4B50",
   "accent2": "#D3D6DB",
   "bg2": "#131518",
   "accentInk": "#FF6266"
  },
  "radius": 0,
  "ornament": "arcs",
  "scale": {
   "cover": 120,
   "title": 64,
   "section": 236,
   "statement": 84,
   "numeral": 108,
   "quote": 54
  },
  "art": {
   "cover": "il-109-map-location",
   "section": "il-day77-pocket-knief",
   "picture": "il-day22-owl",
   "closing": "la-scooter"
  },
  "peeps": [
   "op-peep-19",
   "op-peep-33",
   "op-peep-44",
   "op-peep-57",
   "op-peep-69"
  ]
 },
 "acid": {
  "name": "acid",
  "from": "deck-conference-talk",
  "hint": "acid yellow paper and black, a poster-weight display, one sun; conference talks, manifestos, keynotes, provocation",
  "display": "Anton",
  "dw": 400,
  "body": "Geist",
  "bw": 400,
  "mono": null,
  "accentFace": "Covered By Your Grace",
  "accentWeight": 400,
  "accentSize": 44,
  "paper": {
   "bg": "#E9FF33",
   "ink": "#0B0B0B",
   "muted": "#3F4712",
   "line": "#C4D91C",
   "panel": "#F3FF99",
   "panel2": "#FBFFD4",
   "accent": "#0B0B0B",
   "accent2": "#4A5600",
   "bg2": "#0A0E1B",
   "sun": "#0B0B0B"
  },
  "deep": {
   "bg": "#151515",
   "ink": "#FFFFFF",
   "muted": "#A9A9A9",
   "line": "#2E2E2E",
   "panel": "#1F1F1F",
   "panel2": "#2A2A2A",
   "accent": "#E9FF33",
   "accent2": "#FFFFFF",
   "bg2": "#000000",
   "sun": "#E9FF33"
  },
  "radius": 0,
  "ornament": "sun",
  "scale": {
   "cover": 120,
   "title": 68,
   "section": 260,
   "statement": 88,
   "numeral": 112,
   "quote": 58
  },
  "art": {
   "cover": "il-day22-owl",
   "section": "il-day13-it-girl",
   "picture": "la-relaxing",
   "closing": "la-relaxing"
  },
  "peeps": [
   "op-peep-10",
   "op-peep-19",
   "op-peep-33",
   "op-peep-50",
   "op-peep-77"
  ],
  "charWidth": 0.44
 },
 "chalkboard": {
  "name": "chalkboard",
  "from": "deck-course-lecture",
  "hint": "chalkboard green paper, cream ink and chalk yellow, a schoolroom hand; lectures, courses, teaching, training",
  "display": "Fira Sans",
  "dw": 700,
  "body": "Atkinson Hyperlegible",
  "bw": 400,
  "mono": null,
  "accentFace": "Schoolbell",
  "accentWeight": 400,
  "accentSize": 40,
  "paper": {
   "bg": "#37554D",
   "ink": "#F4F1E8",
   "muted": "#CDD6D0",
   "line": "#516D65",
   "panel": "#3F5F57",
   "panel2": "#4A6B63",
   "accent": "#FFD24A",
   "accent2": "#AED6F1"
  },
  "deep": {
   "bg": "#2E4A42",
   "ink": "#F4F1E8",
   "muted": "#C0CCC6",
   "line": "#46605A",
   "panel": "#3A574F",
   "panel2": "#456760",
   "accent": "#FFD24A",
   "accent2": "#AED6F1",
   "bg2": "#1B2F2A"
  },
  "radius": 6,
  "ornament": "rules",
  "scale": {
   "cover": 112,
   "title": 60,
   "section": 236,
   "statement": 76,
   "numeral": 100,
   "quote": 50
  },
  "art": {
   "cover": "il-day11-blackboard",
   "section": "il-day36-abacus",
   "picture": "il-day15-color-tool",
   "closing": "il-day63-school-bag"
  },
  "peeps": [
   "op-peep-1",
   "op-peep-15",
   "op-peep-57",
   "op-peep-67",
   "op-peep-69"
  ],
  "charWidth": 0.54,
  "strongWeight": 700
 },
 "harbor": {
  "name": "harbor",
  "from": "deck-customer-success",
  "hint": "sand paper, deep teal and burnt orange, a rounded humanist display; customer success, service, accounts, hospitality",
  "display": "Signika",
  "dw": 700,
  "body": "Mulish",
  "bw": 400,
  "mono": null,
  "accentFace": "Kalam",
  "accentWeight": 700,
  "accentSize": 40,
  "paper": {
   "bg": "#F3EDDF",
   "ink": "#0F3A3D",
   "muted": "#4A6A6B",
   "line": "#D5CBB5",
   "panel": "#EAE2CF",
   "panel2": "#DFD5BE",
   "accent": "#D9631A",
   "accent2": "#136F70",
   "accentInk": "#AE4B0E"
  },
  "deep": {
   "bg": "#0F4C50",
   "ink": "#F3EDDF",
   "muted": "#B2CCC9",
   "line": "#215E62",
   "panel": "#165A5E",
   "panel2": "#1D666A",
   "accent": "#F28C3C",
   "accent2": "#7FD3C6",
   "bg2": "#083134",
   "accentInk": "#F8B577"
  },
  "radius": 10,
  "ornament": "dots",
  "scale": {
   "cover": 114,
   "title": 62,
   "section": 236,
   "statement": 80,
   "numeral": 100,
   "quote": 52
  },
  "art": {
   "cover": "la-conversation-illustration",
   "section": "il-day64-followers",
   "picture": "la-woman-working-1",
   "closing": "la-small-character-illustrations"
  },
  "peeps": [
   "op-peep-16",
   "op-peep-94",
   "op-peep-68",
   "op-peep-77",
   "op-peep-31"
  ]
 },
 "violet": {
  "name": "violet",
  "from": "deck-design-review",
  "hint": "white paper, violet and slate grey, a tight modern sans, a dot grid; design reviews, product, UX, critique",
  "display": "Inter Tight",
  "dw": 600,
  "body": "Public Sans",
  "bw": 400,
  "mono": "Geist Mono",
  "accentFace": "Nanum Pen Script",
  "accentWeight": 400,
  "accentSize": 42,
  "paper": {
   "bg": "#FFFFFF",
   "ink": "#17151F",
   "muted": "#5C5968",
   "line": "#E4E2EA",
   "panel": "#F6F5F9",
   "panel2": "#ECEAF1",
   "accent": "#6D28D9",
   "accent2": "#6E6A84",
   "accentInk": "#5B21B6",
   "accent2Ink": "#4E4A63"
  },
  "deep": {
   "bg": "#1E1A2B",
   "ink": "#F7F6FA",
   "muted": "#B5B0C6",
   "line": "#363047",
   "panel": "#29243A",
   "panel2": "#342E47",
   "accent": "#A78BFA",
   "accent2": "#D6D2E4",
   "bg2": "#0F0D18",
   "accentInk": "#C4B5FD"
  },
  "radius": 12,
  "ornament": "dots",
  "scale": {
   "cover": 112,
   "title": 60,
   "section": 236,
   "statement": 78,
   "numeral": 104,
   "quote": 52
  },
  "art": {
   "cover": "il-day94-ui-ux",
   "section": "la-conversation-illustration",
   "picture": "la-website-builder",
   "closing": "la-waitng-illustration"
  },
  "peeps": [
   "op-peep-3",
   "op-peep-20",
   "op-peep-32",
   "op-peep-100",
   "op-peep-24"
  ],
  "charWidth": 0.5
 },
 "gala": {
  "name": "gala",
  "from": "deck-event-proposal",
  "hint": "midnight blue paper, hot pink and champagne, a Bodoni display and a script kicker; events, galas, invitations, fashion, evenings",
  "display": "Bodoni Moda",
  "dw": 800,
  "body": "Jost",
  "bw": 400,
  "mono": null,
  "accentFace": "Parisienne",
  "accentWeight": 400,
  "accentSize": 46,
  "paper": {
   "bg": "#1B2154",
   "ink": "#FBF5EA",
   "muted": "#BCBFDA",
   "line": "#333B7E",
   "panel": "#242B68",
   "panel2": "#2D3576",
   "accent": "#FF3D9E",
   "accent2": "#EACB8A",
   "accentInk": "#FF6DB6",
   "accent2Ink": "#EACB8A"
  },
  "deep": {
   "bg": "#131843",
   "ink": "#FBF5EA",
   "muted": "#B9BCD6",
   "line": "#2A3170",
   "panel": "#1C2360",
   "panel2": "#252D6E",
   "accent": "#FF3D9E",
   "accent2": "#EACB8A",
   "bg2": "#070A24",
   "accentInk": "#FF6DB6",
   "accent2Ink": "#EACB8A"
  },
  "radius": 0,
  "ornament": "watermark",
  "scale": {
   "cover": 112,
   "title": 58,
   "section": 236,
   "statement": 78,
   "numeral": 96,
   "quote": 54
  },
  "art": {
   "cover": "il-day35-firework",
   "section": "il-day86-candle",
   "picture": "la-conversation-illustration",
   "closing": "il-day4-polariod"
  },
  "peeps": [
   "op-peep-89",
   "op-peep-46",
   "op-peep-96",
   "op-peep-11",
   "op-peep-102"
  ],
  "charWidth": 0.52,
  "watermark": "27"
 },
 "brass": {
  "name": "brass",
  "from": "deck-gtm-strategy",
  "hint": "stone paper, olive and brass, a warm serif and arcs; go-to-market, strategy, plans, boardrooms",
  "display": "Vollkorn",
  "dw": 700,
  "body": "Work Sans",
  "bw": 400,
  "mono": null,
  "accentFace": "Gochi Hand",
  "accentWeight": 400,
  "accentSize": 36,
  "paper": {
   "bg": "#ECE8DF",
   "ink": "#16281E",
   "muted": "#4E5A52",
   "line": "#D3CEC2",
   "panel": "#E3DED3",
   "panel2": "#D9D3C6",
   "accent": "#A87A22",
   "accent2": "#2E5C42",
   "accentInk": "#7C5A14"
  },
  "deep": {
   "bg": "#1C3A2E",
   "ink": "#ECE8DF",
   "muted": "#A8B7AC",
   "line": "#2F5142",
   "panel": "#254735",
   "panel2": "#2D5540",
   "accent": "#D3A84E",
   "accent2": "#9CC7A8",
   "bg2": "#0E2119",
   "accentInk": "#E0B95E"
  },
  "radius": 6,
  "ornament": "arcs",
  "scale": {
   "cover": 116,
   "title": 62,
   "section": 236,
   "statement": 80,
   "numeral": 104,
   "quote": 54
  },
  "art": {
   "cover": "il-day65-city-road",
   "section": "il-109-map-location",
   "picture": "il-day14-forklift",
   "closing": "il-day66-travel"
  },
  "peeps": [
   "op-peep-28",
   "op-peep-54",
   "op-peep-70",
   "op-peep-11",
   "op-peep-97"
  ]
 },
 "peach": {
  "name": "peach",
  "from": "deck-hiring-plan",
  "hint": "ivory paper, peach and navy, a soft rounded sans, one corner triangle; hiring, people, HR, onboarding plans",
  "display": "Nunito",
  "dw": 800,
  "body": "Nunito Sans",
  "bw": 400,
  "mono": null,
  "accentFace": "Patrick Hand",
  "accentWeight": 400,
  "accentSize": 38,
  "paper": {
   "bg": "#FBF7EF",
   "ink": "#1B2A4A",
   "muted": "#5C6578",
   "line": "#E1DACB",
   "panel": "#F3EEE3",
   "panel2": "#E9E2D3",
   "accent": "#F2955A",
   "accent2": "#2F4F8F",
   "accentInk": "#B04E14"
  },
  "deep": {
   "bg": "#1F3159",
   "ink": "#FBF7EF",
   "muted": "#B7C0D6",
   "line": "#35486F",
   "panel": "#293D68",
   "panel2": "#324873",
   "accent": "#F5A468",
   "accent2": "#9DBCF2",
   "bg2": "#101B38"
  },
  "radius": 12,
  "ornament": "corner",
  "scale": {
   "cover": 112,
   "title": 60,
   "section": 236,
   "statement": 80,
   "numeral": 104,
   "quote": 54
  },
  "art": {
   "cover": "la-conversation-illustration",
   "section": "il-121-work-from-home-1",
   "picture": "od-sitting-reading",
   "closing": "la-flat-character-illustrations"
  },
  "peeps": [
   "op-peep-90",
   "op-peep-83",
   "op-peep-89",
   "op-peep-24",
   "op-peep-32"
  ]
 },
 "amber": {
  "name": "amber",
  "from": "deck-investor-update",
  "hint": "warm grey paper, amber and charcoal, a plain grotesk, a dot grid; investor updates, monthly reports, candour, numbers",
  "display": "Schibsted Grotesk",
  "dw": 700,
  "body": "Public Sans",
  "bw": 400,
  "mono": "DM Mono",
  "accentFace": "Kalam",
  "accentWeight": 700,
  "accentSize": 32,
  "paper": {
   "bg": "#F4F3EF",
   "ink": "#232326",
   "muted": "#63646A",
   "line": "#D8D6D0",
   "panel": "#EBEAE4",
   "panel2": "#E1DFD8",
   "accent": "#B4700F",
   "accent2": "#4B4C53",
   "accentInk": "#8E5A0A"
  },
  "deep": {
   "bg": "#2B2C31",
   "ink": "#F4F3EF",
   "muted": "#ABAAA5",
   "line": "#3F4046",
   "panel": "#34353B",
   "panel2": "#3D3E45",
   "accent": "#E9A63F",
   "accent2": "#D6D2C8",
   "bg2": "#151618"
  },
  "radius": 4,
  "ornament": "dots",
  "scale": {
   "cover": 108,
   "title": 58,
   "section": 220,
   "statement": 76,
   "numeral": 96,
   "quote": 50
  },
  "art": {
   "cover": "il-day21-lantern",
   "section": "il-day36-abacus",
   "picture": "il-day78-wallet",
   "closing": "il-day6-open-vault"
  },
  "peeps": [
   "op-peep-33",
   "op-peep-68",
   "op-peep-15",
   "op-peep-94",
   "op-peep-2"
  ]
 },
 "magenta": {
  "name": "magenta",
  "from": "deck-marketing-plan",
  "hint": "cream paper, magenta and gold, a Didone display, a corner triangle; marketing, campaigns, creative, brand",
  "display": "DM Serif Display",
  "dw": 400,
  "body": "Work Sans",
  "bw": 400,
  "mono": null,
  "accentFace": "Gochi Hand",
  "accentWeight": 400,
  "accentSize": 38,
  "paper": {
   "bg": "#FBF7F0",
   "ink": "#1E1822",
   "muted": "#665C6B",
   "line": "#E3D9CC",
   "panel": "#F3ECE0",
   "panel2": "#E9DFD0",
   "accent": "#C2185B",
   "accent2": "#E3A91B",
   "accent2Ink": "#7F5B0E"
  },
  "deep": {
   "bg": "#241A2B",
   "ink": "#FBF7F0",
   "muted": "#B7ABBE",
   "line": "#3D2F45",
   "panel": "#2E2237",
   "panel2": "#392B43",
   "accent": "#DA3283",
   "accent2": "#F2C14E",
   "bg2": "#110A16",
   "accentInk": "#FF8AC2"
  },
  "radius": 6,
  "ornament": "corner",
  "scale": {
   "cover": 112,
   "title": 62,
   "section": 230,
   "statement": 78,
   "numeral": 100,
   "quote": 54
  },
  "art": {
   "cover": "il-day17-walkie-talkie",
   "section": "il-day70-designer-fav-tool-wacom",
   "picture": "la-youtube-illustration",
   "closing": "il-day42-imac"
  },
  "peeps": [
   "op-peep-2",
   "op-peep-16",
   "op-peep-19",
   "op-peep-34",
   "op-peep-46"
  ]
 },
 "brick": {
  "name": "brick",
  "from": "deck-nonprofit-impact",
  "hint": "linen paper, brick red and sky blue on a terracotta deep ground, a humanist serif; nonprofits, impact, community, causes",
  "display": "Alegreya",
  "dw": 700,
  "body": "Fira Sans",
  "bw": 400,
  "mono": null,
  "accentFace": "Neucha",
  "accentWeight": 400,
  "accentSize": 40,
  "paper": {
   "bg": "#F2EADB",
   "ink": "#2A211B",
   "muted": "#655648",
   "line": "#D8CBB4",
   "panel": "#E9DFCB",
   "panel2": "#DED2B9",
   "accent": "#B8432A",
   "accent2": "#3F86BE",
   "accentInk": "#8E2F19",
   "accent2Ink": "#245B86"
  },
  "deep": {
   "bg": "#7A3226",
   "ink": "#F6EEDF",
   "muted": "#E3C9BC",
   "line": "#95503F",
   "panel": "#843B2E",
   "panel2": "#8E4638",
   "accent": "#9FCCEC",
   "accent2": "#D9E9F5",
   "bg2": "#471912"
  },
  "radius": 6,
  "ornament": "rules",
  "scale": {
   "cover": 116,
   "title": 62,
   "section": 236,
   "statement": 80,
   "numeral": 104,
   "quote": 54
  },
  "art": {
   "cover": "il-day31-sweet-home",
   "section": "il-day36-abacus",
   "picture": "il-day59-kitchen",
   "closing": "la-small-character-illustrations"
  },
  "peeps": [
   "op-peep-100",
   "op-peep-43",
   "op-peep-102",
   "op-peep-20",
   "op-peep-78"
  ],
  "charWidth": 0.52
 },
 "cobalt": {
  "name": "cobalt",
  "from": "deck-okr-review",
  "hint": "cool white, orange and cobalt, a geometric sans, diagonal stripes; OKRs, scorecards, quarterly reviews, targets",
  "display": "Urbanist",
  "dw": 800,
  "body": "Albert Sans",
  "bw": 400,
  "mono": null,
  "accentFace": "Chakra Petch",
  "accentWeight": 600,
  "accentSize": 32,
  "paper": {
   "bg": "#F3F5F9",
   "ink": "#0C1636",
   "muted": "#586380",
   "line": "#D6DCE8",
   "panel": "#E9EDF4",
   "panel2": "#DDE3EE",
   "accent": "#FF6A1A",
   "accent2": "#2B4DB8",
   "bg2": "#0A0E1B",
   "accentInk": "#B04000"
  },
  "deep": {
   "bg": "#10204F",
   "ink": "#F3F5F9",
   "muted": "#A9B3CC",
   "line": "#27396E",
   "panel": "#182C62",
   "panel2": "#213874",
   "accent": "#FF7A2E",
   "accent2": "#7EAEFF",
   "bg2": "#070D25",
   "accentInk": "#FF9450"
  },
  "radius": 10,
  "ornament": "stripes",
  "scale": {
   "cover": 112,
   "title": 60,
   "section": 230,
   "statement": 76,
   "numeral": 100,
   "quote": 52
  },
  "art": {
   "cover": "il-103-gym-time",
   "section": "il-day36-abacus",
   "picture": "il-day76-watch-spectacle",
   "closing": "il-day11-blackboard"
  },
  "peeps": [
   "op-peep-2",
   "op-peep-16",
   "op-peep-31",
   "op-peep-44",
   "op-peep-68"
  ]
 },
 "butter": {
  "name": "butter",
  "from": "deck-onboarding",
  "hint": "butter yellow paper, teal and marigold, a round chunky display, floating orbs; onboarding, welcome, tours, friendly product",
  "display": "Fredoka",
  "dw": 600,
  "body": "Karla",
  "bw": 400,
  "mono": null,
  "accentFace": "Patrick Hand",
  "accentWeight": 400,
  "accentSize": 40,
  "paper": {
   "bg": "#FFF8E8",
   "ink": "#1E2E33",
   "muted": "#5A6A6F",
   "line": "#EAD9BC",
   "panel": "#FFF1D6",
   "panel2": "#FBE6BF",
   "accent": "#F4B41A",
   "accent2": "#1F8A87",
   "accentInk": "#85580A",
   "accent2Ink": "#16706E",
   "sun": "#F4B41A"
  },
  "deep": {
   "bg": "#146362",
   "ink": "#FFF8E8",
   "muted": "#C6E4DF",
   "line": "#2A7E7C",
   "panel": "#1B6E6C",
   "panel2": "#227977",
   "accent": "#FFC53D",
   "accent2": "#9FE1D8",
   "bg2": "#0B3F3E",
   "accentInk": "#FFD970",
   "accent2Ink": "#C9F0EA",
   "sun": "#FFC53D"
  },
  "radius": 20,
  "ornament": "orbs",
  "scale": {
   "cover": 116,
   "title": 60,
   "section": 236,
   "statement": 80,
   "numeral": 104,
   "quote": 54
  },
  "art": {
   "cover": "il-day31-sweet-home",
   "section": "il-109-map-location",
   "picture": "il-day62-office-bag",
   "closing": "la-hero-image-2"
  },
  "peeps": [
   "op-peep-11",
   "op-peep-90",
   "op-peep-46",
   "op-peep-96",
   "op-peep-102"
  ],
  "charWidth": 0.58
 },
 "rust": {
  "name": "rust",
  "from": "deck-portfolio",
  "hint": "bone paper, rust and near-black, a characterful grotesk with a monogram watermark; portfolios, studios, design, personal work",
  "display": "Syne",
  "dw": 700,
  "body": "Host Grotesk",
  "bw": 400,
  "mono": "Martian Mono",
  "accentFace": "Reenie Beanie",
  "accentWeight": 400,
  "accentSize": 44,
  "paper": {
   "bg": "#F4F1EA",
   "ink": "#151412",
   "muted": "#5B564E",
   "line": "#D9D3C7",
   "panel": "#ECE8DF",
   "panel2": "#E2DDD1",
   "accent": "#C4522B",
   "accent2": "#151412",
   "accentInk": "#A8421F",
   "accent2Ink": "#151412"
  },
  "deep": {
   "bg": "#1C1B18",
   "ink": "#F4F1EA",
   "muted": "#B4AFA4",
   "line": "#35332E",
   "panel": "#26251F",
   "panel2": "#312F29",
   "accent": "#E5734A",
   "accent2": "#F4F1EA",
   "bg2": "#0C0C0A",
   "accentInk": "#EE8A63",
   "accent2Ink": "#F4F1EA"
  },
  "radius": 6,
  "ornament": "watermark",
  "scale": {
   "cover": 116,
   "title": 60,
   "section": 236,
   "statement": 80,
   "numeral": 104,
   "quote": 54
  },
  "art": {
   "cover": "il-day13-it-girl",
   "section": "il-day4-polariod",
   "picture": "il-day78-wallet",
   "closing": "la-coffee"
  },
  "peeps": [
   "op-peep-15",
   "op-peep-31",
   "op-peep-44",
   "op-peep-68",
   "op-peep-94"
  ],
  "charWidth": 0.6,
  "watermark": "A"
 },
 "ember": {
  "name": "ember",
  "from": "deck-product-launch",
  "hint": "sand paper, ember orange and black, a wide heavy display, a corner triangle; launches, countdowns, product reveals, sales kickoffs",
  "display": "Unbounded",
  "dw": 800,
  "body": "Hanken Grotesk",
  "bw": 400,
  "mono": "Martian Mono",
  "accentFace": "Permanent Marker",
  "accentWeight": 400,
  "accentSize": 32,
  "paper": {
   "bg": "#F2E9D8",
   "ink": "#141210",
   "muted": "#5A544B",
   "line": "#D8CCB4",
   "panel": "#EAE0CB",
   "panel2": "#E0D3B8",
   "accent": "#FF4A00",
   "accent2": "#141210",
   "accentInk": "#9E2B00"
  },
  "deep": {
   "bg": "#181614",
   "ink": "#F2E9D8",
   "muted": "#B3AA99",
   "line": "#302B25",
   "panel": "#232019",
   "panel2": "#2E2922",
   "accent": "#FF4A00",
   "accent2": "#F2E9D8",
   "bg2": "#070605",
   "accentInk": "#FF4A00"
  },
  "radius": 4,
  "ornament": "corner",
  "scale": {
   "cover": 92,
   "title": 50,
   "section": 200,
   "statement": 68,
   "numeral": 84,
   "quote": 42
  },
  "art": {
   "cover": "il-day17-walkie-talkie",
   "section": "il-day35-firework",
   "picture": "il-day37-calculator",
   "closing": "il-day97-champagne"
  },
  "peeps": [
   "op-peep-10",
   "op-peep-43",
   "op-peep-69",
   "op-peep-100",
   "op-peep-28"
  ]
 },
 "mint": {
  "name": "mint",
  "from": "deck-product-vision",
  "hint": "lilac white, mint and violet, a geometric sans, arcs; product vision, futures, platforms, technology strategy",
  "display": "Jost",
  "dw": 500,
  "body": "Figtree",
  "bw": 400,
  "mono": null,
  "accentFace": "Shadows Into Light",
  "accentWeight": 400,
  "accentSize": 38,
  "paper": {
   "bg": "#F6F5FC",
   "ink": "#1A1C4F",
   "muted": "#585B88",
   "line": "#DAD8EE",
   "panel": "#ECEAF8",
   "panel2": "#E0DDF4",
   "accent": "#2FBE88",
   "accent2": "#8F78EE",
   "bg2": "#0A0E1B",
   "accentInk": "#0E6E4E",
   "accent2Ink": "#5B45C4"
  },
  "deep": {
   "bg": "#20236B",
   "ink": "#F3F2FC",
   "muted": "#B4B3DC",
   "line": "#373B8A",
   "panel": "#292C7C",
   "panel2": "#343890",
   "accent": "#5EE6B2",
   "accent2": "#CBBCFF",
   "bg2": "#0C0E38"
  },
  "radius": 12,
  "ornament": "arcs",
  "scale": {
   "cover": 112,
   "title": 60,
   "section": 220,
   "statement": 76,
   "numeral": 100,
   "quote": 50
  },
  "art": {
   "cover": "il-day22-owl",
   "section": "il-day21-lantern",
   "picture": "la-best-laptop-reddit",
   "closing": "la-hero-image-2"
  },
  "peeps": [
   "op-peep-11",
   "op-peep-24",
   "op-peep-102",
   "op-peep-43",
   "op-peep-90"
  ]
 },
 "concrete": {
  "name": "concrete",
  "from": "deck-project-kickoff",
  "hint": "concrete grey paper, safety orange and steel blue, a sturdy grotesk with rules; kickoffs, engineering projects, construction, delivery",
  "display": "Chivo",
  "dw": 800,
  "body": "Atkinson Hyperlegible Next",
  "bw": 400,
  "mono": "Overpass Mono",
  "accentFace": "Covered By Your Grace",
  "accentWeight": 400,
  "accentSize": 36,
  "paper": {
   "bg": "#EDEFF1",
   "ink": "#1A2430",
   "muted": "#55626F",
   "line": "#CBD2D9",
   "panel": "#E2E6EA",
   "panel2": "#D5DBE1",
   "accent": "#F26A1B",
   "accent2": "#38658C",
   "accentInk": "#A33C05"
  },
  "deep": {
   "bg": "#2B3B4A",
   "ink": "#F1F3F5",
   "muted": "#A7B3BE",
   "line": "#40505F",
   "panel": "#344656",
   "panel2": "#3D5162",
   "accent": "#FF7A2E",
   "accent2": "#8DB9DC",
   "bg2": "#16202A",
   "accentInk": "#FFA062"
  },
  "radius": 4,
  "ornament": "rules",
  "scale": {
   "cover": 118,
   "title": 62,
   "section": 236,
   "statement": 80,
   "numeral": 104,
   "quote": 54
  },
  "art": {
   "cover": "il-day14-forklift",
   "section": "il-day54-building",
   "picture": "il-day36-abacus",
   "closing": "il-day17-walkie-talkie"
  },
  "peeps": [
   "op-peep-2",
   "op-peep-16",
   "op-peep-19",
   "op-peep-54",
   "op-peep-89"
  ],
  "charWidth": 0.58
 },
 "wine": {
  "name": "wine",
  "from": "deck-research-readout",
  "hint": "ivory paper, wine and warm grey, a Caslon serif with a numeral watermark; research readouts, findings, academia, evidence",
  "display": "Libre Caslon Text",
  "dw": 700,
  "body": "Alegreya Sans",
  "bw": 400,
  "mono": "Courier Prime",
  "accentFace": "Nothing You Could Do",
  "accentWeight": 400,
  "accentSize": 40,
  "paper": {
   "bg": "#F8F6F1",
   "ink": "#2B2724",
   "muted": "#6A635C",
   "line": "#DAD4CB",
   "panel": "#F0ECE5",
   "panel2": "#E6E0D7",
   "accent": "#7A1F2B",
   "accent2": "#857A70",
   "accent2Ink": "#5F564E",
   "sun": "#B8862B"
  },
  "deep": {
   "bg": "#5F1B25",
   "ink": "#F8F6F1",
   "muted": "#D8C2C3",
   "line": "#7B3841",
   "panel": "#6C2531",
   "panel2": "#78303B",
   "accent": "#E8C9A6",
   "accent2": "#CFC3B8",
   "bg2": "#3A0F16",
   "sun": "#E1B25C"
  },
  "radius": 6,
  "ornament": "watermark",
  "scale": {
   "cover": 112,
   "title": 60,
   "section": 236,
   "statement": 80,
   "numeral": 100,
   "quote": 52
  },
  "art": {
   "cover": "la-conversation-illustration",
   "section": "il-day46-experiment-lab",
   "picture": "il-day94-ui-ux",
   "closing": "la-cassette"
  },
  "peeps": [
   "op-peep-19",
   "op-peep-44",
   "op-peep-70",
   "op-peep-97",
   "op-peep-33"
  ],
  "watermark": "14"
 },
 "plum": {
  "name": "plum",
  "from": "deck-retrospective",
  "hint": "warm white paper, plum and sage, a humanist sans, orbs; retrospectives, reflection, wellbeing, learning",
  "display": "Alegreya Sans",
  "dw": 800,
  "body": "Mulish",
  "bw": 400,
  "mono": null,
  "accentFace": "Patrick Hand",
  "accentWeight": 400,
  "accentSize": 40,
  "paper": {
   "bg": "#F6F1E7",
   "ink": "#2B2530",
   "muted": "#6B6270",
   "line": "#DCD3C6",
   "panel": "#EEE8DB",
   "panel2": "#E3DCCB",
   "accent": "#7A4A78",
   "accent2": "#6F8C64",
   "accentInk": "#6A3C68",
   "accent2Ink": "#46623E",
   "sun": "#C8734E"
  },
  "deep": {
   "bg": "#4B2F4F",
   "ink": "#F6F1E7",
   "muted": "#DCD0DC",
   "line": "#63476A",
   "panel": "#573B5C",
   "panel2": "#64476A",
   "accent": "#E8A98A",
   "accent2": "#B7CBA6",
   "bg2": "#2C1A31",
   "accentInk": "#F0BFA6",
   "sun": "#E8A98A"
  },
  "radius": 12,
  "ornament": "orbs",
  "scale": {
   "cover": 116,
   "title": 62,
   "section": 236,
   "statement": 80,
   "numeral": 104,
   "quote": 54
  },
  "art": {
   "cover": "il-day59-kitchen",
   "section": "il-day26-rainbow",
   "picture": "il-day11-blackboard",
   "closing": "il-day30-cafe"
  },
  "peeps": [
   "op-peep-3",
   "op-peep-32",
   "op-peep-50",
   "op-peep-86",
   "op-peep-24"
  ],
  "charWidth": 0.5
 },
 "signal": {
  "name": "signal",
  "from": "deck-roadmap-review",
  "hint": "dark slate paper, signal yellow and periwinkle, a condensed sans with mono figures; roadmaps, engineering reviews, dashboards, dark decks",
  "display": "Barlow Semi Condensed",
  "dw": 700,
  "body": "Barlow",
  "bw": 400,
  "mono": "JetBrains Mono",
  "accentFace": "Share Tech Mono",
  "accentWeight": 400,
  "accentSize": 30,
  "paper": {
   "bg": "#222D40",
   "ink": "#EEF2F8",
   "muted": "#A6B1C5",
   "line": "#344259",
   "panel": "#2A3649",
   "panel2": "#33415A",
   "accent": "#F5D33F",
   "accent2": "#94ADE2",
   "bg2": "#0A0E1B"
  },
  "deep": {
   "bg": "#1A2333",
   "ink": "#EEF2F8",
   "muted": "#9DA9BF",
   "line": "#2B3649",
   "panel": "#212C3E",
   "panel2": "#293650",
   "accent": "#F5D33F",
   "accent2": "#8EA8DE",
   "bg2": "#0B1019"
  },
  "radius": 6,
  "ornament": "arcs",
  "scale": {
   "cover": 112,
   "title": 60,
   "section": 220,
   "statement": 74,
   "numeral": 100,
   "quote": 52
  },
  "art": {
   "cover": "il-109-map-location",
   "section": "il-day65-city-road",
   "picture": "il-day41-desktop",
   "closing": "il-day18-floppy"
  },
  "peeps": [
   "op-peep-11",
   "op-peep-28",
   "op-peep-50",
   "op-peep-70",
   "op-peep-97"
  ],
  "numeralFace": "JetBrains Mono",
  "numeralWeight": 700
 },
 "copper": {
  "name": "copper",
  "from": "deck-sales-qbr",
  "hint": "cream paper, navy and copper, a Bodoni display, a dot grid; sales reviews, pipeline, revenue, quarterly business",
  "display": "Bodoni Moda",
  "dw": 700,
  "body": "Libre Franklin",
  "bw": 400,
  "mono": "JetBrains Mono",
  "accentFace": "Kalam",
  "accentWeight": 700,
  "accentSize": 36,
  "paper": {
   "bg": "#F5EFE6",
   "ink": "#0B1A33",
   "muted": "#4E5A70",
   "line": "#D8CFC0",
   "panel": "#ECE4D7",
   "panel2": "#E2D8C8",
   "accent": "#B4602F",
   "accent2": "#23707C",
   "accentInk": "#964B22"
  },
  "deep": {
   "bg": "#0D1F3C",
   "ink": "#F5EFE6",
   "muted": "#A9B4C8",
   "line": "#26395C",
   "panel": "#16294A",
   "panel2": "#1F3560",
   "accent": "#D98B55",
   "accent2": "#62B5C0",
   "bg2": "#060F22"
  },
  "radius": 4,
  "ornament": "dots",
  "scale": {
   "cover": 116,
   "title": 60,
   "section": 236,
   "statement": 80,
   "numeral": 100,
   "quote": 52
  },
  "art": {
   "cover": "la-sale",
   "section": "il-109-map-location",
   "picture": "la-monitor",
   "closing": "la-hero-image-2"
  },
  "peeps": [
   "op-peep-46",
   "op-peep-94",
   "op-peep-31",
   "op-peep-34",
   "op-peep-78"
  ]
 },
 "terminal": {
  "name": "terminal",
  "from": "deck-sprint-demo",
  "hint": "near-black paper, terminal green and parchment, a mono display and a prompt watermark; sprint demos, developer tools, infrastructure, hacker",
  "display": "JetBrains Mono",
  "dw": 800,
  "body": "Atkinson Hyperlegible Next",
  "bw": 400,
  "mono": "JetBrains Mono",
  "accentFace": "VT323",
  "accentWeight": 400,
  "accentSize": 40,
  "paper": {
   "bg": "#151711",
   "ink": "#EEECE4",
   "muted": "#A5A398",
   "line": "#2E3027",
   "panel": "#1D1F18",
   "panel2": "#272921",
   "accent": "#3DF37C",
   "accent2": "#D9C79B",
   "bg2": "#0A0E1B"
  },
  "deep": {
   "bg": "#0D0E0B",
   "ink": "#ECEAE2",
   "muted": "#9C9A90",
   "line": "#292B23",
   "panel": "#161811",
   "panel2": "#20221A",
   "accent": "#3DF37C",
   "accent2": "#D9C79B",
   "bg2": "#050604"
  },
  "radius": 6,
  "ornament": "watermark",
  "scale": {
   "cover": 90,
   "title": 56,
   "section": 200,
   "statement": 70,
   "numeral": 100,
   "quote": 50
  },
  "art": {
   "cover": "il-day38-macintosh",
   "section": "il-day41-desktop",
   "picture": "il-day17-walkie-talkie",
   "closing": "il-day18-floppy"
  },
  "peeps": [
   "op-peep-33",
   "op-peep-77",
   "op-peep-94",
   "op-peep-19",
   "op-peep-50"
  ],
  "charWidth": 0.6,
  "watermark": ">_"
 },
 "coral": {
  "name": "coral",
  "from": "deck-startup-pitch",
  "hint": "white paper, cobalt and coral with lime on the deep ground, a friendly geometric display; startup pitches, seed rounds, launches, growth",
  "display": "Gabarito",
  "dw": 900,
  "body": "Instrument Sans",
  "bw": 400,
  "mono": "Azeret Mono",
  "accentFace": "Permanent Marker",
  "accentWeight": 400,
  "accentSize": 32,
  "paper": {
   "bg": "#FFFFFF",
   "ink": "#0B1340",
   "muted": "#4A5480",
   "line": "#DFE3F2",
   "panel": "#F2F4FC",
   "panel2": "#E6EAF8",
   "accent": "#0B3BD6",
   "accent2": "#FF5A3A",
   "accent2Ink": "#C2381A",
   "lime": "#C9F23D"
  },
  "deep": {
   "bg": "#0E3ED6",
   "ink": "#FFFFFF",
   "muted": "#CCD5FF",
   "line": "#3A62E6",
   "panel": "#1B4AE0",
   "panel2": "#2757EA",
   "accent": "#CDF546",
   "accent2": "#FF6B4A",
   "bg2": "#071C6E",
   "accent2Ink": "#FFC2B3",
   "lime": "#CDF546"
  },
  "radius": 12,
  "ornament": "corner",
  "scale": {
   "cover": 118,
   "title": 62,
   "section": 236,
   "statement": 80,
   "numeral": 104,
   "quote": 50
  },
  "art": {
   "cover": "il-day5-vault",
   "section": "il-day37-calculator",
   "picture": "il-day94-ui-ux",
   "closing": "il-day6-open-vault"
  },
  "peeps": [
   "op-peep-10",
   "op-peep-28",
   "op-peep-43",
   "op-peep-54",
   "op-peep-70"
  ]
 },
 "lagoon": {
  "name": "lagoon",
  "from": "deck-webinar",
  "hint": "deep teal paper, salmon and aqua, a wide readable sans, diagonal stripes; webinars, live sessions, online education, dark decks",
  "display": "Lexend",
  "dw": 700,
  "body": "DM Sans",
  "bw": 400,
  "mono": null,
  "accentFace": "Mansalva",
  "accentWeight": 400,
  "accentSize": 38,
  "paper": {
   "bg": "#0D343A",
   "ink": "#F1F8F6",
   "muted": "#A9C7C4",
   "line": "#245259",
   "panel": "#14424A",
   "panel2": "#1B4F57",
   "accent": "#FF7B66",
   "accent2": "#5FD8CA",
   "bg2": "#0A0E1B",
   "accentInk": "#FF9A88"
  },
  "deep": {
   "bg": "#082A30",
   "ink": "#F1F8F6",
   "muted": "#9FC0BD",
   "line": "#1B474E",
   "panel": "#0F3940",
   "panel2": "#16464E",
   "accent": "#FF7B66",
   "accent2": "#5FD8CA",
   "bg2": "#031316"
  },
  "radius": 12,
  "ornament": "stripes",
  "scale": {
   "cover": 108,
   "title": 58,
   "section": 220,
   "statement": 76,
   "numeral": 96,
   "quote": 50
  },
  "art": {
   "cover": "il-121-work-from-home-1",
   "section": "il-day41-desktop",
   "picture": "il-day17-walkie-talkie",
   "closing": "la-youtube-illustration"
  },
  "peeps": [
   "op-peep-3",
   "op-peep-15",
   "op-peep-31",
   "op-peep-44",
   "op-peep-68"
  ],
  "charWidth": 0.6
 },
 "marker": {
  "name": "marker",
  "from": "deck-workshop",
  "hint": "warm white paper, marker yellow and black, a black display, stripes; workshops, facilitation, hands-on sessions, playful",
  "display": "Archivo Black",
  "dw": 400,
  "body": "Rubik",
  "bw": 400,
  "mono": null,
  "accentFace": "Gloria Hallelujah",
  "accentWeight": 400,
  "accentSize": 36,
  "paper": {
   "bg": "#FFFDF5",
   "ink": "#111111",
   "muted": "#57544C",
   "line": "#E3E0D5",
   "panel": "#F5F2E8",
   "panel2": "#EBE7DA",
   "accent": "#F5C400",
   "accent2": "#111111",
   "accentInk": "#745600",
   "accent2Ink": "#111111"
  },
  "deep": {
   "bg": "#1B1B1B",
   "ink": "#FFFFFF",
   "muted": "#BDBAB1",
   "line": "#353535",
   "panel": "#262626",
   "panel2": "#303030",
   "accent": "#FFD200",
   "accent2": "#FFF1A8",
   "bg2": "#050505"
  },
  "radius": 6,
  "ornament": "stripes",
  "scale": {
   "cover": 112,
   "title": 60,
   "section": 236,
   "statement": 76,
   "numeral": 100,
   "quote": 50
  },
  "art": {
   "cover": "il-day10-canvas-stand",
   "section": "il-day73-writing-tool",
   "picture": "il-day74-stationary-set",
   "closing": "il-day4-polariod"
  },
  "peeps": [
   "op-peep-2",
   "op-peep-11",
   "op-peep-28",
   "op-peep-33",
   "op-peep-44"
  ],
  "charWidth": 0.64
 },
 "linen": {
  "name": "linen",
  "from": "deck-agenda",
  "hint": "linen paper, copper and teal, an old-style serif with hairlines and a script kicker; agendas, quarterly reviews, meetings, classic",
  "display": "Ibarra Real Nova",
  "dw": 700,
  "body": "Red Hat Text",
  "bw": 400,
  "mono": null,
  "accentFace": "La Belle Aurore",
  "accentWeight": 400,
  "accentSize": 42,
  "paper": {
   "bg": "#F6F0E4",
   "ink": "#1E2540",
   "muted": "#5C5F72",
   "line": "#D9CFBC",
   "panel": "#EEE6D6",
   "panel2": "#E4DAC6",
   "accent": "#B5642F",
   "accent2": "#3F7A72",
   "accentInk": "#8C4418",
   "accent2Ink": "#2E6159",
   "sun": "#D9A26F"
  },
  "deep": {
   "bg": "#26304F",
   "ink": "#F6F0E4",
   "muted": "#B9BDCC",
   "line": "#3B4667",
   "panel": "#2E3A5C",
   "panel2": "#38456B",
   "accent": "#DC9660",
   "accent2": "#8FC7BB",
   "bg2": "#151A30",
   "accentInk": "#E8AB78",
   "sun": "#C97C4B"
  },
  "radius": 4,
  "ornament": "hairlines",
  "scale": {
   "cover": 104,
   "title": 60,
   "section": 236,
   "statement": 80,
   "numeral": 100,
   "quote": 52
  },
  "art": {
   "cover": "il-day76-watch-spectacle",
   "section": "il-day57-reading-room",
   "picture": "il-day79-coffee",
   "closing": "la-waitng-illustration"
  },
  "peeps": [
   "op-peep-100",
   "op-peep-102",
   "op-peep-33",
   "op-peep-44",
   "op-peep-68"
  ],
  "charWidth": 0.5
 },
 "blush": {
  "name": "blush",
  "from": "deck-closing",
  "hint": "blush paper, tomato and royal blue, a modern grotesk, a corner triangle; closings, thanks, calls to action, upbeat",
  "display": "Epilogue",
  "dw": 900,
  "body": "Instrument Sans",
  "bw": 400,
  "mono": "DM Mono",
  "accentFace": "Shantell Sans",
  "accentWeight": 700,
  "accentSize": 40,
  "paper": {
   "bg": "#FFF4EE",
   "ink": "#0F1E66",
   "muted": "#525A85",
   "line": "#F0D8CC",
   "panel": "#FFE9DF",
   "panel2": "#FCDCCE",
   "accent": "#F0553A",
   "accent2": "#1735B2",
   "accentInk": "#B8361F",
   "lime": "#B9E32A"
  },
  "deep": {
   "bg": "#1735B2",
   "ink": "#F8F6F2",
   "muted": "#C5CCF6",
   "line": "#3450D0",
   "panel": "#2244C6",
   "panel2": "#2D50D4",
   "accent": "#FF6B4F",
   "accent2": "#A9C2FF",
   "bg2": "#0A175C",
   "accentInk": "#FFBFAE",
   "lime": "#DDF24A"
  },
  "radius": 6,
  "ornament": "corner",
  "scale": {
   "cover": 128,
   "title": 62,
   "section": 236,
   "statement": 80,
   "numeral": 108,
   "quote": 54
  },
  "art": {
   "cover": "il-day35-firework",
   "section": "la-hero-image-2",
   "picture": "la-waitng-illustration",
   "closing": "il-day17-walkie-talkie"
  },
  "peeps": [
   "op-peep-31",
   "op-peep-44",
   "op-peep-69",
   "op-peep-90",
   "op-peep-15"
  ],
  "charWidth": 0.6
 },
 "burgundy": {
  "name": "burgundy",
  "from": "deck-quote",
  "hint": "cream paper, burgundy and steel blue, a Crimson serif with a quotation-mark watermark; quotes, testimonials, literature, editorial",
  "display": "Crimson Pro",
  "dw": 500,
  "body": "Commissioner",
  "bw": 400,
  "mono": null,
  "accentFace": "Cedarville Cursive",
  "accentWeight": 400,
  "accentSize": 42,
  "paper": {
   "bg": "#F9F3E6",
   "ink": "#1F1A1B",
   "muted": "#655A5B",
   "line": "#DCD1C1",
   "panel": "#F1E9D9",
   "panel2": "#E7DDC9",
   "accent": "#7B1E2B",
   "accent2": "#33506A"
  },
  "deep": {
   "bg": "#2A1F22",
   "ink": "#F6EFE1",
   "muted": "#BDB0AC",
   "line": "#453739",
   "panel": "#34282B",
   "panel2": "#3F3135",
   "accent": "#D8646F",
   "accent2": "#9BBFB7",
   "bg2": "#150F11",
   "accentInk": "#E8969C"
  },
  "radius": 0,
  "ornament": "watermark",
  "scale": {
   "cover": 116,
   "title": 62,
   "section": 236,
   "statement": 80,
   "numeral": 104,
   "quote": 56
  },
  "art": {
   "cover": "il-day57-reading-room",
   "section": "il-day76-watch-spectacle",
   "picture": "od-reading-side",
   "closing": "il-day80-tea"
  },
  "peeps": [
   "op-peep-34",
   "op-peep-77",
   "op-peep-89",
   "op-peep-54",
   "op-peep-10"
  ],
  "charWidth": 0.5,
  "watermark": "”"
 },
 "opera": {
  "name": "opera",
  "from": "deck-section-divider",
  "hint": "cream paper, plum and gold, a Yeseva display with a section-mark watermark and a script kicker; theatre, arts, luxury, chapters",
  "display": "Yeseva One",
  "dw": 400,
  "body": "Raleway",
  "bw": 500,
  "mono": "Cinzel",
  "accentFace": "Great Vibes",
  "accentWeight": 400,
  "accentSize": 46,
  "paper": {
   "bg": "#F7EFE3",
   "ink": "#2B1230",
   "muted": "#6B5570",
   "line": "#E0D2C6",
   "panel": "#F0E5D6",
   "panel2": "#E8DAC7",
   "accent": "#B98A2C",
   "accent2": "#7A2E80",
   "bg2": "#0A0E1B",
   "accentInk": "#7C5813"
  },
  "deep": {
   "bg": "#3B1740",
   "ink": "#F6EAD6",
   "muted": "#CDB6CC",
   "line": "#54305A",
   "panel": "#48214F",
   "panel2": "#54295D",
   "accent": "#E4B858",
   "accent2": "#D4A5E0",
   "bg2": "#1E0B24"
  },
  "radius": 6,
  "ornament": "watermark",
  "scale": {
   "cover": 112,
   "title": 60,
   "section": 236,
   "statement": 78,
   "numeral": 96,
   "quote": 54
  },
  "art": {
   "cover": "il-day21-lantern",
   "section": "il-109-map-location",
   "picture": "od-jumping",
   "closing": "il-day35-firework"
  },
  "peeps": [
   "op-peep-15",
   "op-peep-33",
   "op-peep-68",
   "op-peep-94",
   "op-peep-3"
  ],
  "charWidth": 0.6,
  "strongWeight": 700,
  "watermark": "§"
 },
 "meadow": {
  "name": "meadow",
  "from": "deck-stat",
  "hint": "pale green paper, forest and lime, a tall condensed display, stripes; sustainability, agriculture, health, one big number",
  "display": "Big Shoulders Display",
  "dw": 900,
  "body": "Onest",
  "bw": 400,
  "mono": "Red Hat Mono",
  "accentFace": "Just Another Hand",
  "accentWeight": 400,
  "accentSize": 44,
  "paper": {
   "bg": "#F3F7E8",
   "ink": "#0E2418",
   "muted": "#4A6152",
   "line": "#D2DDC4",
   "panel": "#E8EFD9",
   "panel2": "#DDE7CA",
   "accent": "#1B6A3D",
   "accent2": "#7E9E0C",
   "accent2Ink": "#4F6A00"
  },
  "deep": {
   "bg": "#113626",
   "ink": "#F3F7E8",
   "muted": "#A6BFAD",
   "line": "#24523B",
   "panel": "#193F2E",
   "panel2": "#205238",
   "accent": "#C9F236",
   "accent2": "#93DDAA",
   "bg2": "#061810",
   "lime": "#C9F236"
  },
  "radius": 6,
  "ornament": "stripes",
  "scale": {
   "cover": 116,
   "title": 62,
   "section": 236,
   "statement": 80,
   "numeral": 112,
   "quote": 54
  },
  "art": {
   "cover": "la-sale",
   "section": "il-day70-designer-fav-tool-wacom",
   "picture": "il-day78-wallet",
   "closing": "il-day71-designer-tool-essential"
  },
  "peeps": [
   "op-peep-1",
   "op-peep-57",
   "op-peep-67",
   "op-peep-83",
   "op-peep-95"
  ],
  "charWidth": 0.46
 },
 "sky": {
  "name": "sky",
  "from": "deck-title-modern",
  "hint": "cool grey paper, sky blue and amber, a modern geometric sans, a soft glow; modern business, SaaS, quarterly, clean",
  "display": "Plus Jakarta Sans",
  "dw": 800,
  "body": "Onest",
  "bw": 400,
  "mono": "Geist Mono",
  "accentFace": "Reenie Beanie",
  "accentWeight": 400,
  "accentSize": 46,
  "paper": {
   "bg": "#F3F5F8",
   "ink": "#1B1F26",
   "muted": "#5B6470",
   "line": "#D6DCE4",
   "panel": "#E9EDF2",
   "panel2": "#DDE3EA",
   "accent": "#2C8FD6",
   "accent2": "#E39A3B",
   "bg2": "#E4E9EF",
   "accentInk": "#1A6FAE",
   "accent2Ink": "#9A5F10"
  },
  "deep": {
   "bg": "#2A2F37",
   "ink": "#F3F5F8",
   "muted": "#A5AEBA",
   "line": "#3D444F",
   "panel": "#333944",
   "panel2": "#3E4552",
   "accent": "#9AD6FF",
   "accent2": "#CFE7F7",
   "bg2": "#14171C"
  },
  "radius": 10,
  "ornament": "glow",
  "scale": {
   "cover": 116,
   "title": 60,
   "section": 236,
   "statement": 78,
   "numeral": 104,
   "quote": 52
  },
  "art": {
   "cover": "la-monitor",
   "section": "il-day66-travel",
   "picture": "il-day11-blackboard",
   "closing": "il-day79-coffee"
  },
  "peeps": [
   "op-peep-2",
   "op-peep-16",
   "op-peep-19",
   "op-peep-28",
   "op-peep-11"
  ],
  "charWidth": 0.58
 },
 "marigold": {
  "name": "marigold",
  "from": "product-roadmap-slide",
  "hint": "white paper, blue and marigold, an Overpass sans with mono figures, a dot grid; roadmaps, planning, product, now-next-later",
  "display": "Overpass",
  "dw": 800,
  "body": "Public Sans",
  "bw": 400,
  "mono": "Overpass Mono",
  "accentFace": "Permanent Marker",
  "accentWeight": 400,
  "accentSize": 34,
  "paper": {
   "bg": "#FFFFFF",
   "ink": "#111820",
   "muted": "#4B5563",
   "line": "#D6DCE3",
   "panel": "#F3F5F8",
   "panel2": "#E6EAF0",
   "accent": "#0C5BD1",
   "accent2": "#F5A300",
   "accentInk": "#0A4DB2",
   "accent2Ink": "#7A4E00"
  },
  "deep": {
   "bg": "#0E4FBF",
   "ink": "#FFFFFF",
   "muted": "#C5D6F5",
   "line": "#2F6BD3",
   "panel": "#1B5BC9",
   "panel2": "#2A69D2",
   "accent": "#FFB629",
   "accent2": "#9EC5FF",
   "bg2": "#072E7A",
   "accentInk": "#FFD36A",
   "accent2Ink": "#BBD8FF"
  },
  "radius": 6,
  "ornament": "dots",
  "scale": {
   "cover": 116,
   "title": 60,
   "section": 236,
   "statement": 78,
   "numeral": 104,
   "quote": 52
  },
  "art": {
   "cover": "il-day66-travel",
   "section": "il-day14-forklift",
   "picture": "il-day65-city-road",
   "closing": "la-scooter"
  },
  "peeps": [
   "op-peep-3",
   "op-peep-31",
   "op-peep-44",
   "op-peep-69",
   "op-peep-90"
  ],
  "charWidth": 0.6,
  "numeralFace": "Overpass Mono",
  "numeralWeight": 700
 },
 "atlas": {
  "name": "atlas",
  "from": "kit-atlas",
  "hint": "warm ivory paper, navy and gold, a Playfair serif with fine rules; corporate, investor, annual review, professional",
  "display": "Playfair Display",
  "dw": 700,
  "body": "Source Sans 3",
  "bw": 400,
  "mono": null,
  "accentFace": "Cormorant Garamond",
  "accentWeight": 600,
  "accentSize": 40,
  "paper": {
   "bg": "#F8F5EE",
   "ink": "#14213D",
   "muted": "#5A627A",
   "line": "#DCD6C8",
   "panel": "#EFEBE1",
   "panel2": "#E4DED0",
   "accent": "#C9992A",
   "accent2": "#3E6FCC"
  },
  "deep": {
   "bg": "#182752",
   "ink": "#F8F5EE",
   "muted": "#B4BCD0",
   "line": "#2E3E6A",
   "panel": "#21335F",
   "panel2": "#2A3F73",
   "accent": "#E8B94A",
   "accent2": "#7FA6E8",
   "bg2": "#0C1330"
  },
  "radius": 8,
  "ornament": "rules",
  "scale": {
   "cover": 116,
   "title": 62,
   "section": 236,
   "statement": 80,
   "numeral": 104,
   "quote": 54
  },
  "art": {
   "cover": "la-success-illustration",
   "section": "la-building",
   "picture": "la-woman-working-1",
   "closing": "la-working-2"
  },
  "peeps": [
   "op-peep-84",
   "op-peep-86",
   "op-peep-105",
   "op-peep-53",
   "op-peep-23"
  ]
 },
 "vanta": {
  "name": "vanta",
  "from": "kit-vanta",
  "hint": "near-black paper, lime and violet glow, a grotesk display with mono labels; tech, platforms, engineering, developer audiences",
  "display": "Space Grotesk",
  "dw": 700,
  "body": "IBM Plex Sans",
  "bw": 400,
  "mono": "IBM Plex Mono",
  "accentFace": "IBM Plex Mono",
  "accentWeight": 500,
  "accentSize": 30,
  "paper": {
   "bg": "#0F1526",
   "ink": "#F1F5F9",
   "muted": "#93A0B8",
   "line": "#243049",
   "panel": "#161E33",
   "panel2": "#1E2842",
   "accent": "#C8F542",
   "accent2": "#8F7BFF",
   "bg2": "#0A0E1B"
  },
  "deep": {
   "bg": "#0A0F1F",
   "ink": "#F1F5F9",
   "muted": "#93A0B8",
   "line": "#1E2840",
   "panel": "#121A2E",
   "panel2": "#1A2440",
   "accent": "#C8F542",
   "accent2": "#8F7BFF",
   "bg2": "#04060E"
  },
  "radius": 14,
  "ornament": "glow",
  "scale": {
   "cover": 114,
   "title": 60,
   "section": 220,
   "statement": 76,
   "numeral": 100,
   "quote": 50
  },
  "art": {
   "cover": "la-ai-robot-3",
   "section": "il-111-coding",
   "picture": "la-woman-working-2",
   "closing": "la-free-svg-illustrations-robots"
  },
  "peeps": [
   "op-peep-72",
   "op-peep-9",
   "op-peep-56",
   "op-peep-41",
   "op-peep-55"
  ]
 },
 "folio": {
  "name": "folio",
  "from": "kit-folio",
  "hint": "cream paper, vermilion and forest with a sun disc, a Fraunces serif and a hand kicker; editorial, studios, brand, magazines",
  "display": "Fraunces",
  "dw": 600,
  "body": "Inter",
  "bw": 400,
  "mono": null,
  "accentFace": "Caveat",
  "accentWeight": 600,
  "accentSize": 44,
  "paper": {
   "bg": "#F5EFE4",
   "ink": "#1C1A17",
   "muted": "#6B655C",
   "line": "#DACFBE",
   "panel": "#EDE4D4",
   "panel2": "#E3D8C3",
   "accent": "#E0492B",
   "accent2": "#2C6B58",
   "sun": "#F4C15D"
  },
  "deep": {
   "bg": "#221E1A",
   "ink": "#F5EFE4",
   "muted": "#B0A798",
   "line": "#3E3831",
   "panel": "#2C2723",
   "panel2": "#38322C",
   "accent": "#F26A48",
   "accent2": "#8CC7AE",
   "bg2": "#100E0C",
   "sun": "#F4C15D"
  },
  "radius": 0,
  "ornament": "hairlines",
  "scale": {
   "cover": 120,
   "title": 66,
   "section": 260,
   "statement": 84,
   "numeral": 108,
   "quote": 56
  },
  "art": {
   "cover": "la-guy-with-glasses",
   "section": "il-day73-writing-tool",
   "picture": "la-doodle",
   "closing": "la-coffee"
  },
  "peeps": [
   "op-peep-58",
   "op-peep-47",
   "op-peep-73",
   "op-peep-84",
   "op-peep-86"
  ]
 },
 "pulse": {
  "name": "pulse",
  "from": "kit-pulse",
  "hint": "white paper and an electric blue deep ground, coral and lime, a heavy geometric display, colour blocks; startups, pitches, bold launches, youth",
  "display": "Sora",
  "dw": 800,
  "body": "Manrope",
  "bw": 500,
  "mono": null,
  "accentFace": "Bricolage Grotesque",
  "accentWeight": 800,
  "accentSize": 36,
  "paper": {
   "bg": "#FFFFFF",
   "ink": "#0B0B14",
   "muted": "#5B5B70",
   "line": "#E4E4EE",
   "panel": "#F3F3F9",
   "panel2": "#E9E9F4",
   "accent": "#FF4D2E",
   "accent2": "#2B2BFF",
   "lime": "#B9F542"
  },
  "deep": {
   "bg": "#2B2BFF",
   "ink": "#FFFFFF",
   "muted": "#CFCFFF",
   "line": "#5050FF",
   "panel": "#3A3AFF",
   "panel2": "#4A48FF",
   "accent": "#FF4D2E",
   "accent2": "#B9F542",
   "bg2": "#6A2BFF",
   "accentInk": "#B9F542",
   "lime": "#B9F542"
  },
  "radius": 24,
  "ornament": "blocks",
  "scale": {
   "cover": 122,
   "title": 68,
   "section": 250,
   "statement": 82,
   "numeral": 112,
   "quote": 54
  },
  "art": {
   "cover": "la-free-svg-illustration-rocket",
   "section": "il-day20-rocket",
   "picture": "la-hero-image-2",
   "closing": "la-scooter"
  },
  "peeps": [
   "op-peep-105",
   "op-peep-53",
   "op-peep-23",
   "op-peep-72",
   "op-peep-9"
  ]
 },
 "terra": {
  "name": "terra",
  "from": "kit-terra",
  "hint": "warm sand paper, terracotta and moss on a pine deep ground, a rounded sans with blobs; community, sustainability, nonprofit, warm",
  "display": "Outfit",
  "dw": 700,
  "body": "Nunito Sans",
  "bw": 400,
  "mono": null,
  "accentFace": "Caveat",
  "accentWeight": 600,
  "accentSize": 46,
  "paper": {
   "bg": "#F8F0E3",
   "ink": "#2F2A25",
   "muted": "#786C5F",
   "line": "#DDD0BB",
   "panel": "#EFE4D0",
   "panel2": "#E5D8BF",
   "accent": "#E0703F",
   "accent2": "#5F8F5A",
   "sun": "#F2C063"
  },
  "deep": {
   "bg": "#2F4A36",
   "ink": "#F8F0E3",
   "muted": "#BBC9B4",
   "line": "#456249",
   "panel": "#3A5A40",
   "panel2": "#466B4C",
   "accent": "#F2905E",
   "accent2": "#A9D2A0",
   "bg2": "#1D3124",
   "sun": "#F2C063"
  },
  "radius": 28,
  "ornament": "blobs",
  "scale": {
   "cover": 118,
   "title": 64,
   "section": 240,
   "statement": 80,
   "numeral": 108,
   "quote": 54
  },
  "art": {
   "cover": "il-day96-camping",
   "section": "il-day53-farm",
   "picture": "la-house-illustrations",
   "closing": "la-scooter"
  },
  "peeps": [
   "op-peep-56",
   "op-peep-41",
   "op-peep-55",
   "op-peep-58",
   "op-peep-47"
  ]
 },
 "slate": {
  "name": "slate",
  "from": "kit-slate",
  "hint": "white paper, one blue and black, a Swiss grotesk with crosshairs and square corners; agencies, proposals, minimal, portfolio",
  "display": "Archivo",
  "dw": 700,
  "body": "Archivo",
  "bw": 400,
  "mono": null,
  "accentFace": "Space Mono",
  "accentWeight": 400,
  "accentSize": 26,
  "paper": {
   "bg": "#FFFFFF",
   "ink": "#111111",
   "muted": "#6B6B6B",
   "line": "#E2E2E2",
   "panel": "#F3F3F3",
   "panel2": "#E9E9E9",
   "accent": "#2F6BFF",
   "accent2": "#111111"
  },
  "deep": {
   "bg": "#181818",
   "ink": "#FFFFFF",
   "muted": "#A0A0A0",
   "line": "#2E2E2E",
   "panel": "#1F1F1F",
   "panel2": "#2A2A2A",
   "accent": "#4D82FF",
   "accent2": "#FFFFFF",
   "bg2": "#070707"
  },
  "radius": 0,
  "ornament": "crosshairs",
  "scale": {
   "cover": 118,
   "title": 60,
   "section": 236,
   "statement": 78,
   "numeral": 104,
   "quote": 52
  },
  "art": {
   "cover": "la-working-1",
   "section": "il-day10-canvas-stand",
   "picture": "la-desk-illustration-2",
   "closing": "la-flat-character-illustrations"
  },
  "peeps": [
   "op-peep-73",
   "op-peep-84",
   "op-peep-86",
   "op-peep-105",
   "op-peep-53"
  ]
 }
};

/** The style names, in vocabulary order. */
export const kitStyleNames: string[] = ["campfire","sunny","ledger","parchment","newsprint","casebook","graphite","acid","chalkboard","harbor","violet","gala","brass","peach","amber","magenta","brick","cobalt","butter","rust","ember","mint","concrete","wine","plum","signal","copper","terminal","coral","lagoon","marker","linen","blush","burgundy","opera","meadow","sky","marigold","atlas","vanta","folio","pulse","terra","slate"];
