package storagecli

import (
	"bytes"
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"hycanvas/backend/internal/storage"
)

// fakeDriver is an in-memory storage.Driver for exercising the copy engine.
type fakeDriver struct {
	objects map[string][]byte
	putErr  map[string]int // key -> number of Put calls that should fail
	puts    int
}

func newFakeDriver() *fakeDriver {
	return &fakeDriver{objects: map[string][]byte{}, putErr: map[string]int{}}
}

func (f *fakeDriver) Kind() string { return "fake" }
func (f *fakeDriver) Put(key string, data []byte) (storage.PutResult, error) {
	f.puts++
	if n := f.putErr[key]; n > 0 {
		f.putErr[key] = n - 1
		return storage.PutResult{}, errors.New("simulated put failure")
	}
	f.objects[key] = append([]byte(nil), data...)
	return storage.PutResult{Key: key, Size: int64(len(data))}, nil
}
func (f *fakeDriver) Get(key string) ([]byte, error) { return f.objects[key], nil }
func (f *fakeDriver) Delete(key string) error        { delete(f.objects, key); return nil }
func (f *fakeDriver) Exists(key string) (bool, error) {
	_, ok := f.objects[key]
	return ok, nil
}

// seedTree writes a small local storage layout and returns its base.
func seedTree(t *testing.T) string {
	t.Helper()
	base := t.TempDir()
	files := map[string]string{
		"assets/ws1/a.png":                "png-bytes",
		"assets/ws1/b.jpg":                "jpg-bytes",
		"designs/d1/snapshots/abc.ocd":    "snapshot",
		"designs/d1/exports/video-j1.mp4": "video-bytes",
		"designs/d2/snapshots/deadbe.ocd": "snapshot-2",
	}
	for rel, content := range files {
		full := filepath.Join(base, filepath.FromSlash(rel))
		if err := os.MkdirAll(filepath.Dir(full), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(full, []byte(content), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	return base
}

func TestListTreeDerivesKeys(t *testing.T) {
	base := seedTree(t)
	keys, total, err := listTree(base)
	if err != nil {
		t.Fatal(err)
	}
	if len(keys) != 5 {
		t.Fatalf("keys = %v, want 5", keys)
	}
	for _, k := range keys {
		if strings.Contains(k, "\\") || strings.HasPrefix(k, "/") {
			t.Errorf("key %q is not a clean slash-relative path", k)
		}
	}
	if total == 0 {
		t.Error("total bytes not accumulated")
	}
}

func TestMigrateTreeCopiesAndSkips(t *testing.T) {
	base := seedTree(t)
	dst := newFakeDriver()
	dst.objects["assets/ws1/a.png"] = []byte("already-there")

	var out bytes.Buffer
	rep, err := migrateTree(base, dst, &out)
	if err != nil {
		t.Fatal(err)
	}
	if rep.Copied != 4 || rep.Skipped != 1 || len(rep.Failed) != 0 {
		t.Fatalf("report = %+v", rep)
	}
	if string(dst.objects["designs/d1/snapshots/abc.ocd"]) != "snapshot" {
		t.Error("snapshot content not copied")
	}
	// The pre-existing object must not be overwritten (skip semantics).
	if string(dst.objects["assets/ws1/a.png"]) != "already-there" {
		t.Error("existing object was overwritten instead of skipped")
	}
	if !strings.Contains(out.String(), "already present, skipped") {
		t.Errorf("skip not reported:\n%s", out.String())
	}

	missing, err := verifyTree(base, dst)
	if err != nil {
		t.Fatal(err)
	}
	if len(missing) != 0 {
		t.Errorf("verify missing = %v", missing)
	}
}

func TestMigrateTreeRetriesOnce(t *testing.T) {
	base := seedTree(t)
	dst := newFakeDriver()
	dst.putErr["assets/ws1/b.jpg"] = 1                // first attempt fails, retry succeeds
	dst.putErr["designs/d1/exports/video-j1.mp4"] = 2 // both attempts fail

	var out bytes.Buffer
	rep, err := migrateTree(base, dst, &out)
	if err != nil {
		t.Fatal(err)
	}
	if rep.Copied != 4 {
		t.Errorf("copied = %d, want 4 (retry must recover b.jpg)", rep.Copied)
	}
	if len(rep.Failed) != 1 || !strings.Contains(rep.Failed[0], "video-j1.mp4") {
		t.Errorf("failed = %v, want just the video", rep.Failed)
	}
}

func TestPatchEnvPreservesUnrelatedLines(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, ".env")
	original := `# Generated by the wizard
NODE_ENV=production
PORT=8006

# Database
DATABASE_URL=postgresql://u:p@h/db

# Storage
STORAGE_DRIVER=local
LOCAL_STORAGE_PATH=/srv/data

# Email
SMTP_HOST=mail.example.com
SMTP_PASSWORD="hunter two"
`
	if err := os.WriteFile(path, []byte(original), 0o600); err != nil {
		t.Fatal(err)
	}
	err := patchEnv(path, []kv{
		{"STORAGE_DRIVER", "s3"},
		{"S3_ENDPOINT", "minio:9000"},
		{"S3_BUCKET", "hycanvas"},
		{"S3_ACCESS_KEY_ID", "ak"},
		{"S3_SECRET_ACCESS_KEY", "s k"}, // needs quoting
	})
	if err != nil {
		t.Fatal(err)
	}
	got, _ := os.ReadFile(path)
	s := string(got)

	for _, want := range []string{
		"NODE_ENV=production",
		"DATABASE_URL=postgresql://u:p@h/db",
		"SMTP_HOST=mail.example.com",
		"SMTP_PASSWORD=\"hunter two\"",
		"LOCAL_STORAGE_PATH=/srv/data", // kept: it is the rollback pointer
		"STORAGE_DRIVER=s3",
		"S3_ENDPOINT=minio:9000",
		"S3_SECRET_ACCESS_KEY=\"s k\"",
		"# Generated by the wizard",
	} {
		if !strings.Contains(s, want) {
			t.Errorf("patched env missing %q:\n%s", want, s)
		}
	}
	if strings.Contains(s, "STORAGE_DRIVER=local") {
		t.Error("old driver assignment survived")
	}
	if strings.Count(s, "STORAGE_DRIVER=") != 1 {
		t.Error("driver key duplicated")
	}
	info, _ := os.Stat(path)
	if info.Mode().Perm() != 0o600 {
		t.Errorf("perms = %o, want 600", info.Mode().Perm())
	}
}

func TestRunArgErrors(t *testing.T) {
	var out, errBuf bytes.Buffer
	if code := Run(nil, os.Stdin, &out, &errBuf); code != 2 {
		t.Errorf("no args: code = %d, want 2", code)
	}
	if !strings.Contains(errBuf.String(), "usage:") {
		t.Errorf("usage missing: %q", errBuf.String())
	}
	errBuf.Reset()
	if code := Run([]string{"teleport"}, os.Stdin, &out, &errBuf); code != 2 {
		t.Errorf("unknown verb: code = %d, want 2", code)
	}
}

func TestHumanBytes(t *testing.T) {
	if got := humanBytes(512); got != "512 B" {
		t.Errorf("512 = %q", got)
	}
	if got := humanBytes(2 * 1024 * 1024); got != "2.0 MB" {
		t.Errorf("2MiB = %q", got)
	}
}
