// Code generated by scripts/gen-theme.mjs from frontend/src/theme.config.mjs; DO NOT EDIT.

package realtime

// presencePalette is the stable per-user color palette, single-sourced with
// the frontend via theme.config.mjs. Order is meaningful: changing it
// reassigns existing users' colors, so append rather than reorder.
var presencePalette = []string{
	"#ef4444",
	"#f97316",
	"#eab308",
	"#22c55e",
	"#06b6d4",
	"#3b82f6",
	"#8b5cf6",
	"#ec4899",
	"#14b8a6",
	"#a855f7",
}
