package setup

import (
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"os"
	"strings"
)

// GenerateToken returns a 64-hex-char secret suitable for JWT_SECRET/AI_SECRET.
func GenerateToken() string {
	b := make([]byte, 32)
	if _, err := rand.Read(b); err != nil {
		panic(err) // crypto/rand failing means the host is unusable
	}
	return hex.EncodeToString(b)
}

// envLine renders one KEY=value line, quoting values godotenv would otherwise
// misparse (spaces, #, quotes).
func envLine(key, value string) string {
	if strings.ContainsAny(value, " #\"'\n\t") {
		value = "\"" + strings.NewReplacer("\\", "\\\\", "\"", "\\\"", "\n", "\\n").Replace(value) + "\""
	}
	return key + "=" + value + "\n"
}

// renderEnv builds the .env content from the wizard's answers. Only what the
// operator chose is written; everything else keeps its documented default.
func renderEnv(body completeRequest, dsn, jwtSecret, aiSecret string) string {
	var b strings.Builder
	b.WriteString("# Generated by the HyCanvas first-run setup wizard.\n")
	b.WriteString("# See .env.example for the full reference of available settings.\n\n")

	b.WriteString("# Server\n")
	b.WriteString(envLine("NODE_ENV", "production"))
	if body.Port != "" {
		b.WriteString(envLine("PORT", body.Port))
	}
	if body.BindHost != "" {
		// Behind a reverse proxy the app only needs to listen for the proxy,
		// typically on 127.0.0.1.
		b.WriteString(envLine("BIND_HOST", body.BindHost))
	}
	if body.AppURL != "" {
		b.WriteString(envLine("APP_URL", strings.TrimRight(body.AppURL, "/")))
		// A production cookie is Secure by default; on a plain-http origin the
		// browser would drop it and login silently fails. An https public URL
		// (e.g. a TLS-terminating proxy) keeps Secure cookies.
		if strings.HasPrefix(body.AppURL, "http://") {
			b.WriteString(envLine("COOKIE_SECURE", "false"))
		}
	}
	b.WriteString("\n# Database\n")
	b.WriteString(envLine("DATABASE_URL", dsn))

	b.WriteString("\n# Secrets (auto-generated)\n")
	b.WriteString(envLine("JWT_SECRET", jwtSecret))
	b.WriteString(envLine("AI_SECRET", aiSecret))

	b.WriteString("\n# Storage\n")
	if body.Storage.Driver == "s3" {
		b.WriteString(envLine("STORAGE_DRIVER", "s3"))
		b.WriteString(envLine("S3_ENDPOINT", body.Storage.S3.Endpoint))
		if body.Storage.S3.Region != "" {
			b.WriteString(envLine("S3_REGION", body.Storage.S3.Region))
		}
		b.WriteString(envLine("S3_BUCKET", body.Storage.S3.Bucket))
		b.WriteString(envLine("S3_ACCESS_KEY_ID", body.Storage.S3.AccessKey))
		b.WriteString(envLine("S3_SECRET_ACCESS_KEY", body.Storage.S3.SecretKey))
		if body.Storage.S3.ForcePathStyle {
			b.WriteString(envLine("S3_FORCE_PATH_STYLE", "true"))
		}
	} else {
		b.WriteString(envLine("STORAGE_DRIVER", "local"))
		if body.Storage.LocalPath != "" {
			b.WriteString(envLine("LOCAL_STORAGE_PATH", body.Storage.LocalPath))
		}
	}

	if body.SMTP.Enabled && body.SMTP.Host != "" {
		b.WriteString("\n# Email (SMTP)\n")
		b.WriteString(envLine("SMTP_HOST", body.SMTP.Host))
		if body.SMTP.Port != "" {
			b.WriteString(envLine("SMTP_PORT", body.SMTP.Port))
		}
		if body.SMTP.Username != "" {
			b.WriteString(envLine("SMTP_USERNAME", body.SMTP.Username))
			b.WriteString(envLine("SMTP_PASSWORD", body.SMTP.Password))
		}
		if body.SMTP.From != "" {
			b.WriteString(envLine("SMTP_FROM", body.SMTP.From))
		}
		if body.SMTP.FromName != "" {
			b.WriteString(envLine("SMTP_FROM_NAME", body.SMTP.FromName))
		}
	}
	return b.String()
}

// writeEnvFile writes the .env atomically (tmp + rename) with 0600 perms so
// a crash mid-write can never leave a half-written config.
func writeEnvFile(dest, content string) error {
	tmp := dest + ".tmp"
	if err := os.WriteFile(tmp, []byte(content), 0o600); err != nil {
		return fmt.Errorf("write %s: %w", tmp, err)
	}
	if err := os.Rename(tmp, dest); err != nil {
		_ = os.Remove(tmp)
		return fmt.Errorf("rename into place: %w", err)
	}
	return nil
}
