package secrets

import (
	"crypto/rand"
	"testing"
)

// Fixtures generated by Node's node:crypto (the source of truth) using the exact
// algorithms in accounts/password.ts and ai/crypto.ts. If these pass, the Go
// implementation is byte-compatible with what the NestJS backend wrote.
const (
	fxPassword = "hunter2"
	fxPWHash   = "scrypt$f24fb3e57554c48a455476b1385eeeb3$e9109f4526cb21d7ef1b7b31cc4e395f07b5a134b6ae89d557b6b6dbc6d4cfa321736774759a79eff894e5c647e45ae40bf30b06c286daaebb65524e1cbf941b"

	fxAISecret = "test-ai-secret"
	fxAIPlain  = "sk-live-abc123"
	fxAICipher = "QWHr5xKx6nGRrFniL9Y="
	fxAIIV     = "fMxirjhyljOi9VOS"
	fxAITag    = "swdpzufawJ7NrzW5gOKURQ=="
)

func TestVerifyPassword_NodeFixture(t *testing.T) {
	if !VerifyPassword(fxPassword, fxPWHash) {
		t.Fatal("correct password failed to verify against the Node-produced hash")
	}
	if VerifyPassword("wrong-password", fxPWHash) {
		t.Fatal("wrong password verified (must fail)")
	}
	if VerifyPassword(fxPassword, "garbage") || VerifyPassword(fxPassword, "bcrypt$x$y") {
		t.Fatal("malformed/foreign hash must not verify")
	}
}

func TestDecryptAISecret_NodeFixture(t *testing.T) {
	got, err := DecryptAISecret(Encrypted{Cipher: fxAICipher, IV: fxAIIV, Tag: fxAITag}, fxAISecret)
	if err != nil {
		t.Fatalf("decrypt failed: %v", err)
	}
	if got != fxAIPlain {
		t.Fatalf("decrypt mismatch: got %q want %q", got, fxAIPlain)
	}
	if _, err := DecryptAISecret(Encrypted{Cipher: fxAICipher, IV: fxAIIV, Tag: fxAITag}, "wrong-secret"); err == nil {
		t.Fatal("decrypt with wrong secret must fail (GCM auth)")
	}
}

func TestEncryptDecryptRoundTrip(t *testing.T) {
	nonce := make([]byte, 12)
	if _, err := rand.Read(nonce); err != nil {
		t.Fatal(err)
	}
	enc, err := EncryptAISecret("my-secret-value", "k", nonce)
	if err != nil {
		t.Fatal(err)
	}
	got, err := DecryptAISecret(enc, "k")
	if err != nil {
		t.Fatal(err)
	}
	if got != "my-secret-value" {
		t.Fatalf("round-trip mismatch: %q", got)
	}
}

func TestHashToken(t *testing.T) {
	// sha256("token") known digest.
	const want = "3c469e9d6c5875d37a43f353d4f88e61fcf812c66eee3457465a40b0da4153e0"
	if got := HashToken("token"); got != want {
		t.Fatalf("HashToken mismatch: got %s want %s", got, want)
	}
}
