// Package whiteboard owns server-authoritative whiteboard voting (F30
// FR-19/FR-20). It is the single place vote sessions and dot-votes are read and
// written, gated by the sharing access resolver:
//   - reading a tally requires `view`,
//   - casting/toggling a dot-vote requires `comment` (participant level),
//   - opening/closing/revealing a session requires `edit` (facilitator level).
//
// Integrity the CRDT meta cannot give (per-user budgets, no double-voting,
// enforced anonymity/reveal) lives here in Postgres; the board's client meta
// keeps only ephemeral display state. After every mutation a realtime
// vote-changed signal is broadcast so connected clients refetch the tally over
// REST (the same pattern as comments). Per-workspace isolation is enforced at
// the query layer via the design id, which the HTTP layer resolves the caller's
// access to before any read/write.
package whiteboard

import (
	"context"
	"errors"

	"hycanvas/backend/internal/authz"
	"hycanvas/backend/internal/sharing"
)

// Errors map to RFC 7807 statuses at the HTTP layer.
var (
	ErrForbidden  = errors.New("forbidden")
	ErrNotFound   = errors.New("not found")
	ErrBadRequest = errors.New("bad request")
	// ErrConflict is a 409: the session is closed, or the caller is out of budget.
	ErrConflict = errors.New("conflict")
)

const (
	defaultBudget = 3
	maxBudget     = 99
)

// Access resolves a caller's capabilities on a design (sharing slice A).
type Access interface {
	GetAccess(ctx context.Context, designID, userID string) (sharing.DesignAccessView, error)
}

// Realtime broadcasts a vote-changed signal so connected clients refetch. Nil
// hook = skip (REST still works).
type Realtime interface {
	NotifyVoteChanged(ctx context.Context, designID string)
}

// VoteRepo is the persistence surface (satisfied by the pgx repository and by an
// in-memory fake in tests). All methods are design/session scoped.
type VoteRepo interface {
	CreateSession(ctx context.Context, s SessionRow) (SessionRow, error)
	GetSession(ctx context.Context, designID, sessionID string) (SessionRow, error)
	SetSessionState(ctx context.Context, designID, sessionID string, open, revealed bool) (SessionRow, error)
	HasVote(ctx context.Context, sessionID, nodeID, userID string) (bool, error)
	CountUserVotes(ctx context.Context, sessionID, userID string) (int, error)
	// InsertVote atomically inserts a vote ONLY if the user is still under
	// `budget` (a single guarded statement, so concurrent casts on distinct nodes
	// cannot push the per-user count past the budget). Returns whether a row was
	// inserted (false = lost the budget race or a duplicate node).
	InsertVote(ctx context.Context, sessionID, designID, nodeID, userID string, budget int) (bool, error)
	DeleteVote(ctx context.Context, sessionID, nodeID, userID string) error
	// Votes returns every cast in a session (node + user), for tally + reveal.
	Votes(ctx context.Context, sessionID string) ([]CastRow, error)
}

// SessionRow mirrors the WhiteboardVoteSession table.
type SessionRow struct {
	ID            string
	DesignID      string
	BudgetPerUser int
	Anonymous     bool
	Revealed      bool
	Open          bool
	CreatedByID   *string
}

// CastRow is one dot-vote (node + voter).
type CastRow struct {
	NodeID string
	UserID string
}

// Service is the whiteboard voting module.
type Service struct {
	repo     VoteRepo
	access   Access
	realtime Realtime
}

// NewService wires the voting service. realtime may be nil. Row ids are
// generated by the repository (DB-side gen_random_uuid()).
func NewService(repo VoteRepo, access Access, realtime Realtime) *Service {
	return &Service{repo: repo, access: access, realtime: realtime}
}

func hasCap(access sharing.DesignAccessView, c authz.Capability) bool {
	for _, cap := range access.Capabilities {
		if cap == c {
			return true
		}
	}
	return false
}

// assertCapability resolves the caller's design access and checks `cap`. A
// missing `view` reads as NotFound (don't reveal the design exists); any other
// missing capability is Forbidden.
func (s *Service) assertCapability(ctx context.Context, designID, userID string, cap authz.Capability) error {
	access, err := s.access.GetAccess(ctx, designID, userID)
	if err != nil {
		// Only a genuine "design not found" is a 404; a transient DB/infra error
		// must surface as 500, not be masked as a missing design.
		if errors.Is(err, sharing.ErrNotFound) {
			return ErrNotFound
		}
		return err
	}
	if !hasCap(access, cap) {
		if cap == authz.CapView {
			return ErrNotFound
		}
		return ErrForbidden
	}
	return nil
}

// SessionView is the API shape of a vote session.
type SessionView struct {
	ID            string `json:"id"`
	DesignID      string `json:"designId"`
	BudgetPerUser int    `json:"budgetPerUser"`
	Anonymous     bool   `json:"anonymous"`
	Revealed      bool   `json:"revealed"`
	Open          bool   `json:"open"`
}

func view(s SessionRow) SessionView {
	return SessionView{ID: s.ID, DesignID: s.DesignID, BudgetPerUser: s.BudgetPerUser, Anonymous: s.Anonymous, Revealed: s.Revealed, Open: s.Open}
}

// TallyView is a session's standings for one viewer. Counts are always present;
// `mine` is the caller's own picks (always visible to them); `voters` (who voted
// each node) is included only once the session is revealed and not anonymous.
type TallyView struct {
	Session         SessionView         `json:"session"`
	Counts          map[string]int      `json:"counts"`
	Mine            []string            `json:"mine"`
	RemainingBudget int                 `json:"remainingBudget"`
	Voters          map[string][]string `json:"voters,omitempty"`
}

// OpenSession opens a new vote round on a design (facilitator/edit only).
func (s *Service) OpenSession(ctx context.Context, designID, userID string, budgetPerUser int, anonymous bool) (SessionView, error) {
	if err := s.assertCapability(ctx, designID, userID, authz.CapEdit); err != nil {
		return SessionView{}, err
	}
	if budgetPerUser <= 0 {
		budgetPerUser = defaultBudget
	}
	if budgetPerUser > maxBudget {
		budgetPerUser = maxBudget
	}
	uid := userID
	row, err := s.repo.CreateSession(ctx, SessionRow{
		DesignID:      designID,
		BudgetPerUser: budgetPerUser,
		Anonymous:     anonymous,
		Open:          true,
		CreatedByID:   &uid,
	})
	if err != nil {
		return SessionView{}, err
	}
	s.notifyChanged(ctx, designID)
	return view(row), nil
}

// SetSessionState closes/reopens and/or reveals a session (facilitator/edit
// only). Closing also implies the round is over; revealing exposes voters.
func (s *Service) SetSessionState(ctx context.Context, designID, sessionID, userID string, open, revealed bool) (SessionView, error) {
	if err := s.assertCapability(ctx, designID, userID, authz.CapEdit); err != nil {
		return SessionView{}, err
	}
	if _, err := s.repo.GetSession(ctx, designID, sessionID); err != nil {
		return SessionView{}, ErrNotFound
	}
	row, err := s.repo.SetSessionState(ctx, designID, sessionID, open, revealed)
	if err != nil {
		return SessionView{}, err
	}
	s.notifyChanged(ctx, designID)
	return view(row), nil
}

// CastVote toggles the caller's dot-vote on a node (participant/comment level).
// Re-casting the same node removes the vote; a new vote is rejected (409) when
// the session is closed or the caller is out of budget. Returns the refreshed
// tally for the caller.
func (s *Service) CastVote(ctx context.Context, designID, sessionID, nodeID, userID string) (TallyView, error) {
	if err := s.assertCapability(ctx, designID, userID, authz.CapComment); err != nil {
		return TallyView{}, err
	}
	if nodeID == "" {
		return TallyView{}, ErrBadRequest
	}
	sess, err := s.repo.GetSession(ctx, designID, sessionID)
	if err != nil {
		return TallyView{}, ErrNotFound
	}
	if !sess.Open {
		return TallyView{}, ErrConflict // voting is closed
	}
	has, err := s.repo.HasVote(ctx, sessionID, nodeID, userID)
	if err != nil {
		return TallyView{}, err
	}
	if has {
		if err := s.repo.DeleteVote(ctx, sessionID, nodeID, userID); err != nil {
			return TallyView{}, err
		}
	} else {
		// Fast-path budget check for the common case + the 409 message; the real
		// guard is the atomic guarded insert below, which prevents two concurrent
		// distinct-node casts from pushing the count past the budget.
		spent, err := s.repo.CountUserVotes(ctx, sessionID, userID)
		if err != nil {
			return TallyView{}, err
		}
		if spent >= sess.BudgetPerUser {
			return TallyView{}, ErrConflict // out of budget
		}
		inserted, err := s.repo.InsertVote(ctx, sessionID, designID, nodeID, userID, sess.BudgetPerUser)
		if err != nil {
			return TallyView{}, err
		}
		if !inserted {
			return TallyView{}, ErrConflict // lost the budget race
		}
	}
	s.notifyChanged(ctx, designID)
	return s.tally(ctx, sess, userID)
}

// Tally returns the current standings for a viewer (view level).
func (s *Service) Tally(ctx context.Context, designID, sessionID, userID string) (TallyView, error) {
	if err := s.assertCapability(ctx, designID, userID, authz.CapView); err != nil {
		return TallyView{}, err
	}
	sess, err := s.repo.GetSession(ctx, designID, sessionID)
	if err != nil {
		return TallyView{}, ErrNotFound
	}
	return s.tally(ctx, sess, userID)
}

// tally builds the standings, enforcing anonymity/reveal server-side: voter
// identities are exposed only when the session is revealed and not anonymous.
func (s *Service) tally(ctx context.Context, sess SessionRow, viewerID string) (TallyView, error) {
	casts, err := s.repo.Votes(ctx, sess.ID)
	if err != nil {
		return TallyView{}, err
	}
	counts := map[string]int{}
	mine := []string{}
	spent := 0
	var voters map[string][]string
	reveal := sess.Revealed && !sess.Anonymous
	if reveal {
		voters = map[string][]string{}
	}
	for _, c := range casts {
		counts[c.NodeID]++
		if c.UserID == viewerID {
			mine = append(mine, c.NodeID)
			spent++
		}
		if reveal {
			voters[c.NodeID] = append(voters[c.NodeID], c.UserID)
		}
	}
	remaining := sess.BudgetPerUser - spent
	if remaining < 0 {
		remaining = 0
	}
	return TallyView{Session: view(sess), Counts: counts, Mine: mine, RemainingBudget: remaining, Voters: voters}, nil
}

func (s *Service) notifyChanged(ctx context.Context, designID string) {
	if s.realtime != nil {
		s.realtime.NotifyVoteChanged(ctx, designID)
	}
}
