// AUTO-GENERATED by scripts/gen-theme.mjs from src/theme.config.mjs. Do not edit by hand.
// Edit colors in src/theme.config.mjs, then run `npm run gen:theme`.

export const brand = {
  "50": "#FBEFF7",
  "100": "#F6DDEE",
  "200": "#EDBBDC",
  "300": "#E195C7",
  "400": "#CF67A8",
  "500": "#B73E88",
  "600": "#9B2C72",
  "700": "#7E2059",
  "800": "#681A49",
  "900": "#54163B",
  "950": "#3E1030",
} as const;

export const accent = {
  "50": "#FCEAF4",
  "100": "#FAD5E9",
  "200": "#F4AFD3",
  "300": "#EE8FC2",
  "400": "#E07AB8",
  "500": "#D6409A",
  "600": "#B82F80",
  "700": "#8E2563",
  "800": "#6B1C4A",
  "900": "#4F1537",
  "950": "#350D24",
} as const;

/** Editor canvas overlay colors (React-rendered SVG/CSS overlays; the engine
 *  cannot read CSS, so these are imported as data). `selection` is a
 *  deliberate cool hue kept distinct from the brand so selections stay
 *  legible against brand-colored content. */
export const overlay = {
  selection: "#2563eb",
  guideSubtle: "#3b82f6",
  guideActive: "#06b6d4",
  guideConflict: "#f43f5e",
  penPreview: "#a855f7",
  ruler: "#9ca3af",
} as const;

/** Collaborator presence palette (assigned by a stable hash; shared with the
 *  Go backend via presence_palette_gen.go). */
export const presencePalette = [
  "#ef4444",
  "#f97316",
  "#eab308",
  "#22c55e",
  "#06b6d4",
  "#3b82f6",
  "#8b5cf6",
  "#ec4899",
  "#14b8a6",
  "#a855f7",
] as const;
export const presenceFallback = "#ef4444";

/** Avatar swatches (a distinct rainbow for telling collaborators apart). */
export const avatarColors = [
  "#e11d48",
  "#ea580c",
  "#d97706",
  "#16a34a",
  "#0891b2",
  "#2563eb",
  "#7c3aed",
  "#db2777",
] as const;
