package crdt

import (
	"encoding/base64"
	"encoding/json"
	"os"
	"testing"
)

// The fixture is generated by testdata/gen.mjs with the real client libraries
// (yjs + @hc/realtime): journaled-style update frames plus the DesignFile the
// CLIENT fold produces for them. Equality here proves the embedded goja fold
// is byte-identical to the browser's.
func loadFixture(t *testing.T) (frames [][]byte, expected json.RawMessage) {
	t.Helper()
	raw, err := os.ReadFile("testdata/fixture.json")
	if err != nil {
		t.Fatalf("read fixture: %v", err)
	}
	var fx struct {
		Updates  []string        `json:"updates"`
		Expected json.RawMessage `json:"expected"`
	}
	if err := json.Unmarshal(raw, &fx); err != nil {
		t.Fatalf("parse fixture: %v", err)
	}
	for _, u := range fx.Updates {
		b, err := base64.StdEncoding.DecodeString(u)
		if err != nil {
			t.Fatalf("decode frame: %v", err)
		}
		frames = append(frames, b)
	}
	return frames, fx.Expected
}

func TestFoldUpdatesMatchesClientFold(t *testing.T) {
	frames, expected := loadFixture(t)
	got, err := FoldUpdates(frames)
	if err != nil {
		t.Fatalf("FoldUpdates: %v", err)
	}
	// Compare canonically (key order in JSON.stringify vs encoding/json could
	// differ); the trees must be deeply equal.
	var gotAny, wantAny any
	if err := json.Unmarshal(got, &gotAny); err != nil {
		t.Fatalf("fold output is not JSON: %v\n%s", err, got)
	}
	if err := json.Unmarshal(expected, &wantAny); err != nil {
		t.Fatalf("fixture expected is not JSON: %v", err)
	}
	gotC, _ := json.Marshal(gotAny)
	wantC, _ := json.Marshal(wantAny)
	if string(gotC) != string(wantC) {
		t.Fatalf("fold mismatch\n got: %s\nwant: %s", gotC, wantC)
	}
}

func TestFoldUpdatesEmpty(t *testing.T) {
	got, err := FoldUpdates(nil)
	if err != nil {
		t.Fatalf("FoldUpdates(nil): %v", err)
	}
	if string(got) != "{}" {
		t.Fatalf("empty fold = %s, want {}", got)
	}
}

// A GAPPED log must refuse. Yjs parks deltas with missing dependencies and
// keeps going, so dropping an early frame still projects a plausible file that
// silently omits content; folding that into a snapshot would roll a design's
// current state backwards. The journal really can have holes (a client drops
// sends while its socket is down and reconverges over the unjournaled sync
// handshake), so this is the guard that keeps the last-leave fold honest.
func TestFoldUpdatesRefusesGappedLog(t *testing.T) {
	frames, _ := loadFixture(t)
	if len(frames) < 2 {
		t.Fatalf("fixture has %d frames; need at least 2 to make a gap", len(frames))
	}
	gapped := frames[1:] // the first frame never reached the journal
	if _, err := FoldUpdates(gapped); err == nil {
		t.Fatal("folded a gapped log into a snapshot instead of refusing")
	}
	// The complete log still folds, so the guard is not simply refusing everything.
	if _, err := FoldUpdates(frames); err != nil {
		t.Fatalf("complete log must still fold: %v", err)
	}
}

func TestFoldUpdatesGarbageFrame(t *testing.T) {
	// A garbage frame must surface as an error, not a panic or silent success.
	if _, err := FoldUpdates([][]byte{{0xff, 0xfe, 0xfd}}); err == nil {
		t.Fatal("expected an error for a garbage frame")
	}
}
